hmcts/opal-fines-service

charts/opal-account-enquiry/Chart.yaml, charts/opal-account-enquiry/values.yaml
=> Correct another reference

Jenkinsfile_CNP, charts/opal-account-enquiry/Chart.yaml, charts/opal-account-enquiry/values.yaml, src/main/resources/application.yaml
Fixes the failing master pipelines.
```
[ ] Yes
[x] No
```
=> Disable DB migration on pipeline, instead run on app startup

README.md, charts/opal-account-enquiry/Chart.yaml, charts/opal-account-enquiry/values.dev.template.yaml, charts/opal-account-enquiry/values.yaml, docker-compose.yml, infrastructure/main.tf, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/opal/dev/ContainerConfiguration.java
PO-46
Rename database to opal-fines-db
```
[x] Yes
[] No
```
=> PO-46: Rename database to opal-fines-db

src/main/java/uk/gov/hmcts/opal/controllers/DefendantAccountController.java, src/main/java/uk/gov/hmcts/opal/service/DefendantAccountService.java, src/test/java/uk/gov/hmcts/opal/controllers/DefendantAccountControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/DefendantAccountServiceTest.java
Optimise and cleanup code
```
[ ] Yes
[x] No
```
=> Optimise and cleanup code

postman/DefendantAccount.postman_collection.json, src/main/java/uk/gov/hmcts/opal/controllers/DefendantAccountController.java, src/main/java/uk/gov/hmcts/opal/repository/DefendantAccountRepository.java, src/main/java/uk/gov/hmcts/opal/service/DefendantAccountService.java, src/test/java/uk/gov/hmcts/opal/controllers/DefendantAccountControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/DefendantAccountServiceTest.java
=> Retrive multiple accounts by business unit

docker-compose.yml
Reverts hmcts/opal-fines-service#44
=> Revert "chore(deps): update postgres docker tag to v16"

build.gradle, config/owasp/suppressions.xml
PO-71- Fix CVE issues
```
[ ] Yes
[x] No
```
=> PO-71- Fix CVE issues

src/main/resources/db/migration/V20231113_005__insert_notes.sql, src/main/resources/db/migration/V20231117_007__insert_sample_defendant_accounts.sql
=> PO-40-add-dummy-data-insert-scripts

bin/utils/launchdarkly-flags.json, build.gradle, src/integrationTest/java/uk/gov/hmcts/opal/openapi/OpenAPIPublisherTest.java, src/main/java/uk/gov/hmcts/opal/Application.java, src/main/java/uk/gov/hmcts/opal/config/AopConfig.java, src/main/java/uk/gov/hmcts/opal/config/LaunchDarklyConfiguration.java, src/main/java/uk/gov/hmcts/opal/controllers/TestingSupportController.java, src/main/java/uk/gov/hmcts/opal/launchdarkly/FeatureToggle.java, src/main/java/uk/gov/hmcts/opal/launchdarkly/FeatureToggleApi.java, src/main/java/uk/gov/hmcts/opal/launchdarkly/FeatureToggleAspect.java, src/main/java/uk/gov/hmcts/opal/launchdarkly/FeatureToggleService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/opal/config/LaunchDarklyConfigurationTest.java, src/test/java/uk/gov/hmcts/opal/controllers/TestingSupportControllerTest.java, src/test/java/uk/gov/hmcts/opal/launchdarkly/FeatureToggleApiTest.java, src/test/java/uk/gov/hmcts/opal/launchdarkly/FeatureToggleAspectTest.java, src/test/java/uk/gov/hmcts/opal/launchdarkly/FeatureToggleServiceTest.java
PO-96
Add Launch darkly Client for backend
```
[ ] Yes
[x] No
```
=> PO-96: Add Launch darkly Client for backend

build.gradle
=> Remove gradle build warning

build.gradle
This reverts commit 96e987a548bbce12f9224d908daca3b07bc40b5e.
```
[ ] Yes
[ ] No
```
=> Revert "chore(deps): update plugin uk.gov.hmcts.java to v0.12.49"

build.gradle
https://tools.hmcts.net/jira/browse/PO-134
Fix CVE in Opal-fines-service
```
[ ] Yes
[ X] No
```
=> Resolve Spring and tomcat CVE's with version upgrade

src/main/java/uk/gov/hmcts/opal/controllers/DefendantAccountController.java, src/main/java/uk/gov/hmcts/opal/dto/AccountSearchDto.java, src/main/java/uk/gov/hmcts/opal/dto/AccountSearchResultsDto.java, src/main/java/uk/gov/hmcts/opal/dto/AccountSummaryDto.java, src/main/java/uk/gov/hmcts/opal/service/DefendantAccountService.java, src/test/java/uk/gov/hmcts/opal/controllers/DefendantAccountControllerTest.java, src/test/java/uk/gov/hmcts/opal/dto/AccountSearchDtoTest.java, src/test/java/uk/gov/hmcts/opal/dto/AccountSearchResultsDtoTest.java, src/test/java/uk/gov/hmcts/opal/dto/AccountSummaryDtoTest.java, src/test/java/uk/gov/hmcts/opal/service/DefendantAccountServiceTest.java
=> Establish new API endpoint.

src/main/java/uk/gov/hmcts/opal/launchdarkly/FeatureToggleApi.java
=> Remove code that creates a deprecated warning

src/main/java/uk/gov/hmcts/opal/launchdarkly/FeatureToggleApi.java, src/test/java/uk/gov/hmcts/opal/launchdarkly/FeatureToggleApiTest.java
PO-135
Fix Deprecation warnings for Launch Darkly
```
[ ] Yes
[x] No
```
=> PO-135: Fix Deprecation warnings for Launch Darkly

src/main/java/uk/gov/hmcts/opal/controllers/DefendantAccountController.java, src/main/java/uk/gov/hmcts/opal/dto/AccountDetailsDto.java, src/main/java/uk/gov/hmcts/opal/entity/BusinessUnitsEntity.java, src/main/java/uk/gov/hmcts/opal/entity/CourtsEntity.java, src/main/java/uk/gov/hmcts/opal/entity/DebtorDetailEntity.java, src/main/java/uk/gov/hmcts/opal/entity/DefendantAccountEntity.java, src/main/java/uk/gov/hmcts/opal/entity/DefendantAccountPartiesEntity.java, src/main/java/uk/gov/hmcts/opal/entity/EnforcersCourtsBaseEntity.java, src/main/java/uk/gov/hmcts/opal/entity/EnforcersEntity.java, src/main/java/uk/gov/hmcts/opal/entity/NoteEntity.java, src/main/java/uk/gov/hmcts/opal/entity/PartyEntity.java, src/main/java/uk/gov/hmcts/opal/entity/PaymentTermsEntity.java, src/main/java/uk/gov/hmcts/opal/repository/BusinessUnitsRepository.java, src/main/java/uk/gov/hmcts/opal/repository/CourtsRepository.java, src/main/java/uk/gov/hmcts/opal/repository/DebtorDetailRepository.java, src/main/java/uk/gov/hmcts/opal/repository/DefendantAccountPartiesRepository.java, src/main/java/uk/gov/hmcts/opal/repository/DefendantAccountRepository.java, src/main/java/uk/gov/hmcts/opal/repository/EnforcersRepository.java, src/main/java/uk/gov/hmcts/opal/repository/NoteRepository.java, src/main/java/uk/gov/hmcts/opal/repository/PaymentTermsRepository.java, src/main/java/uk/gov/hmcts/opal/service/DefendantAccountService.java, src/main/java/uk/gov/hmcts/opal/util/NamesUtil.java, src/test/java/uk/gov/hmcts/opal/controllers/DefendantAccountControllerTest.java, src/test/java/uk/gov/hmcts/opal/entity/DefendantAccountEntityTest.java, src/test/java/uk/gov/hmcts/opal/service/DefendantAccountServiceTest.java, src/test/java/uk/gov/hmcts/opal/util/NamesUtilTest.java
=> All enitites and repos required for accountdetails response population

src/main/java/uk/gov/hmcts/opal/controllers/PartyController.java, src/main/java/uk/gov/hmcts/opal/entity/DefendantAccountEntity.java, src/main/java/uk/gov/hmcts/opal/entity/DefendantAccountPartiesEntity.java, src/main/java/uk/gov/hmcts/opal/entity/DefendantAccountSummary.java, src/main/java/uk/gov/hmcts/opal/entity/PartyEntity.java, src/main/java/uk/gov/hmcts/opal/entity/PartySummary.java, src/main/java/uk/gov/hmcts/opal/repository/DefendantAccountRepository.java, src/main/java/uk/gov/hmcts/opal/repository/PartyRepository.java, src/main/java/uk/gov/hmcts/opal/service/DefendantAccountService.java, src/main/java/uk/gov/hmcts/opal/service/LegacyPartyService.java, src/main/java/uk/gov/hmcts/opal/service/PartyService.java, src/main/java/uk/gov/hmcts/opal/service/PartyServiceInterface.java, src/main/java/uk/gov/hmcts/opal/service/PartyServiceProxy.java, src/test/java/uk/gov/hmcts/opal/entity/DefendantAccountSummaryTest.java, src/test/java/uk/gov/hmcts/opal/service/DefendantAccountServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/LegacyPartyServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/PartyServiceProxyTest.java, src/test/java/uk/gov/hmcts/opal/service/PartyServiceTest.java
=> Add Entities to DB Annotations for Party -> DefendantAccount

src/main/java/uk/gov/hmcts/opal/authentication/config/internal/InternalAuthConfigurationProperties.java, src/main/java/uk/gov/hmcts/opal/authentication/config/internal/InternalAuthProviderConfigurationProperties.java, src/main/resources/application.yaml
=> code cleanup

build.gradle, src/main/java/uk/gov/hmcts/opal/service/LegacyNoteService.java, src/test/java/uk/gov/hmcts/opal/service/LegacyNoteServiceTest.java
Add gateway url to request, previously was just the path not the full url
https://tools.hmcts.net/jira/browse/PO-43
```
[ ] Yes
[ X] No
```
=> Po 43 requests to legacy gateway

src/main/resources/application.yaml
```
[ ] Yes
[*] Maybe
[ ] No
```
=> Don't send JSON dates as timestamps

src/main/java/uk/gov/hmcts/opal/dto/AccountSummaryDto.java, src/main/resources/tempSearchData.json
=> Add account id into account summary response from search

.gitignore, build.gradle, src/main/java/uk/gov/hmcts/opal/dto/AccountSearchResultsDto.java, src/main/java/uk/gov/hmcts/opal/dto/DateDto.java, src/main/java/uk/gov/hmcts/opal/entity/DefendantAccountEntity.java, src/main/java/uk/gov/hmcts/opal/entity/DefendantAccountPartiesEntity.java, src/main/java/uk/gov/hmcts/opal/entity/DefendantAccountSummary.java, src/main/java/uk/gov/hmcts/opal/entity/PartyEntity.java, src/main/java/uk/gov/hmcts/opal/repository/DefendantAccountRepository.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/DefendantAccountSpecs.java, src/main/java/uk/gov/hmcts/opal/service/DefendantAccountService.java, src/main/java/uk/gov/hmcts/opal/service/PartyServiceInterface.java, src/test/java/uk/gov/hmcts/opal/dto/AccountSearchDtoTest.java, src/test/java/uk/gov/hmcts/opal/dto/AccountSearchResultsDtoTest.java, src/test/java/uk/gov/hmcts/opal/entity/DefendantAccountEntityTest.java, src/test/java/uk/gov/hmcts/opal/entity/PartyEntityTest.java, src/test/java/uk/gov/hmcts/opal/repository/jpa/DefendantAccountSpecsTest.java, src/test/java/uk/gov/hmcts/opal/service/DefendantAccountServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/PartyServiceTest.java
=> Add initial DefendantAccount search parameters

postman/Account Enquiry.postman_collection.json, src/main/java/uk/gov/hmcts/opal/dto/AccountDetailsDto.java, src/main/java/uk/gov/hmcts/opal/dto/PartyDto.java, src/main/java/uk/gov/hmcts/opal/entity/BusinessUnitsEntity.java, src/main/java/uk/gov/hmcts/opal/entity/CourtsEntity.java, src/main/java/uk/gov/hmcts/opal/entity/DefendantAccountEntity.java, src/main/java/uk/gov/hmcts/opal/entity/DefendantAccountPartiesEntity.java, src/main/java/uk/gov/hmcts/opal/entity/EnforcersEntity.java, src/main/java/uk/gov/hmcts/opal/entity/NoteEntity.java, src/main/java/uk/gov/hmcts/opal/entity/PaymentTermsEntity.java, src/main/java/uk/gov/hmcts/opal/repository/DefendantAccountPartiesRepository.java, src/main/java/uk/gov/hmcts/opal/repository/PaymentTermsRepository.java, src/main/java/uk/gov/hmcts/opal/service/DefendantAccountService.java, src/test/java/uk/gov/hmcts/opal/dto/PartyDtoTest.java, src/test/java/uk/gov/hmcts/opal/entity/PartyEntityTest.java, src/test/java/uk/gov/hmcts/opal/service/DefendantAccountServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/LegacyPartyServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/PartyServiceTest.java
[
](https://tools.hmcts.net/jira/browse/PO-130)
```
[ ] Yes
[ X] No
```
=> PO-130: rework to align with capita

src/main/java/uk/gov/hmcts/opal/entity/DefendantAccountSummary.java, src/main/java/uk/gov/hmcts/opal/entity/FullNameBuilder.java, src/main/java/uk/gov/hmcts/opal/entity/PartyEntity.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/DefendantAccountSpecs.java, src/main/java/uk/gov/hmcts/opal/service/DefendantAccountService.java, src/test/java/uk/gov/hmcts/opal/entity/DefendantAccountSummaryTest.java
=> Add initials field to search response

src/functionalTest/java/uk/gov/hmcts/opal/steps/DefendantSearchApiStepDef.java, src/functionalTest/java/uk/gov/hmcts/opal/steps/defendantSearchApiStepDef.java, src/functionalTest/resources/features/defendantAccountSearchAPI.feature
https://tools.hmcts.net/jira/browse/PO-119
automated tests for PO-119 defendant account search
=> automated tests for PO-119

src/main/java/uk/gov/hmcts/opal/controllers/DefendantAccountController.java, src/main/java/uk/gov/hmcts/opal/dto/AccountEnquiryDto.java, src/main/java/uk/gov/hmcts/opal/dto/ToJsonString.java, src/main/java/uk/gov/hmcts/opal/service/DefendantAccountService.java, src/main/java/uk/gov/hmcts/opal/service/DefendantAccountServiceInterface.java, src/main/java/uk/gov/hmcts/opal/service/DefendantAccountServiceProxy.java, src/main/java/uk/gov/hmcts/opal/service/LegacyDefendantAccountService.java, src/main/java/uk/gov/hmcts/opal/service/LegacyNoteService.java, src/main/java/uk/gov/hmcts/opal/service/LegacyPartyService.java, src/main/java/uk/gov/hmcts/opal/service/LegacyService.java, src/test/java/uk/gov/hmcts/opal/service/DefendantAccountServiceProxyTest.java, src/test/java/uk/gov/hmcts/opal/service/LegacyPartyServiceTest.java
=> Add skeleton account servicce interface, legacy & proxy

src/main/java/uk/gov/hmcts/opal/dto/AccountDetailsDto.java, src/main/java/uk/gov/hmcts/opal/service/DefendantAccountService.java, src/main/resources/tempDetailsData.json, src/test/java/uk/gov/hmcts/opal/service/DefendantAccountServiceTest.java
https://tools.hmcts.net/jira/browse/PO-130
Remove account type and arrears from account details
```
[ ] Yes
[ X] No
```
=> remove account type and arrears

src/test/java/uk/gov/hmcts/opal/service/LegacyDefendantAccountServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/LegacyPartyServiceTest.java
=> Add unit tests for LegacyDefendantAccountService

schemas/AccountDetails/details_in_json.json, schemas/AccountDetails/details_out_json.json, schemas/AccountDetails/of_f_get_defendant_account_in.xsd, schemas/AccountDetails/of_f_get_defendant_account_out.xsd, schemas/AccountSearch/of_f_search_defendant_accounts_in.xsd, schemas/AccountSearch/of_f_search_defendant_accounts_out.xsd, schemas/AccountSearch/search_in_json.json, schemas/AccountSearch/search_out_json.json
Schema definitions from capita
```
[ ] Yes
[X ] No
```
=> add schemas from capita to repo

src/functionalTest/java/uk/gov/hmcts/opal/steps/DefendantAccountDetailsStefDef.java, src/functionalTest/resources/features/defendantAccountDetailsAPI.feature
https://tools.hmcts.net/jira/browse/PO-130
Automated tests for PO-130
=> Po 130 automated tests

src/main/java/uk/gov/hmcts/opal/authentication/config/SecurityConfig.java, src/main/java/uk/gov/hmcts/opal/controllers/DefendantAccountController.java, src/main/java/uk/gov/hmcts/opal/service/DefendantAccountService.java, src/main/java/uk/gov/hmcts/opal/service/DefendantAccountServiceProxy.java, src/main/java/uk/gov/hmcts/opal/service/LegacyDefendantAccountService.java
This allows us to use the  EnableWebSecurity with debug=true, as well as providing some extra logging to aid with tracing errors.
```
[ ] Yes
[*] No
```
=> Added extra logging & debug

charts/opal-fines-service/values.stg.template.yaml
=> Update frontend url to staging

src/main/java/uk/gov/hmcts/opal/config/rest/RestClientConfiguration.java, src/main/java/uk/gov/hmcts/opal/service/LegacyDefendantAccountService.java, src/main/java/uk/gov/hmcts/opal/service/LegacyNoteService.java, src/main/java/uk/gov/hmcts/opal/service/LegacyPartyService.java, src/main/java/uk/gov/hmcts/opal/service/LegacyService.java, src/test/java/uk/gov/hmcts/opal/service/LegacyDefendantAccountServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/LegacyNoteServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/LegacyPartyServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/LegacyProxyNoteServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/LegacyTestsBase.java
=> Use RestClient instead of RestTemplate

src/main/java/uk/gov/hmcts/opal/service/LegacyDefendantAccountService.java, src/main/java/uk/gov/hmcts/opal/service/LegacyPartyService.java, src/main/java/uk/gov/hmcts/opal/service/LegacyService.java, src/test/java/uk/gov/hmcts/opal/service/LegacyDefendantAccountServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/LegacyPartyServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/LegacyServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/LegacyTestsBase.java
=> Requests to Gateway need to jsonify parameters

src/main/java/uk/gov/hmcts/opal/controllers/NoteController.java, src/main/java/uk/gov/hmcts/opal/dto/NoteDto.java, src/main/java/uk/gov/hmcts/opal/dto/legacy/LegacySaveNoteRequestDto.java, src/main/java/uk/gov/hmcts/opal/dto/legacy/LegacySaveNoteResponseDto.java, src/main/java/uk/gov/hmcts/opal/service/LegacyGatewayResponseException.java, src/main/java/uk/gov/hmcts/opal/service/LegacyNoteService.java, src/main/java/uk/gov/hmcts/opal/service/LegacyService.java, src/main/java/uk/gov/hmcts/opal/service/NoteService.java, src/main/java/uk/gov/hmcts/opal/service/PartyService.java, src/test/java/uk/gov/hmcts/opal/service/LegacyDefendantAccountServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/LegacyNoteServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/LegacyPartyServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/LegacyProxyNoteServiceTest.java
This PR also takes the opportunity to improve the error handling around the Legacy Gateway requests/responses
```
[*] Yes
[ ] No
```
=> Update Account Note Service

src/main/java/uk/gov/hmcts/opal/authentication/config/SecurityConfig.java
=> Disable security for testing support controller

src/main/java/uk/gov/hmcts/opal/controllers/DefendantAccountController.java, src/main/java/uk/gov/hmcts/opal/dto/AddNoteDto.java, src/test/java/uk/gov/hmcts/opal/controllers/DefendantAccountControllerTest.java
=> Add new 'addNote' endpoint for DefendantAccounts

src/main/java/uk/gov/hmcts/opal/dto/AccountDetailsDto.java, src/main/java/uk/gov/hmcts/opal/dto/legacy/AccountActivityDto.java, src/main/java/uk/gov/hmcts/opal/dto/legacy/LegacyAccountDetailsResponseDto.java, src/main/java/uk/gov/hmcts/opal/repository/NoteRepository.java, src/main/java/uk/gov/hmcts/opal/service/DefendantAccountService.java, src/test/java/uk/gov/hmcts/opal/service/DefendantAccountServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/LegacyDefendantAccountServiceTest.java, src/test/resources/schemas/AccountDetails/of_f_get_defendant_account_in.json, src/test/resources/schemas/AccountDetails/of_f_get_defendant_account_out.json, src/test/resources/schemas/AccountDetails/of_f_get_defendant_account_out.xsd, src/test/resources/schemas/AccountNotes/of_create_note_in.json, src/test/resources/schemas/AccountNotes/of_create_note_out.json, src/test/resources/schemas/AccountSearch/of_f_search_defendant_accounts_in.json, src/test/resources/schemas/AccountSearch/of_f_search_defendant_accounts_out.json, src/test/resources/schemas/AccountSearch/of_f_search_defendant_accounts_out.xsd
https://tools.hmcts.net/jira/browse/PO-138
```
[ ] Yes
[ X] No
```
=> update schemas, update defendantaccount details service to retrieve notes

src/main/java/uk/gov/hmcts/opal/controllers/DefendantAccountController.java, src/main/java/uk/gov/hmcts/opal/dto/NoteDto.java, src/main/java/uk/gov/hmcts/opal/dto/legacy/LegacySaveNoteRequestDto.java, src/main/java/uk/gov/hmcts/opal/service/LegacyNoteService.java, src/test/java/uk/gov/hmcts/opal/controllers/DefendantAccountControllerTest.java
=> Populate added Note with request RemoteUser

README.md
=> Add required env variable in ReadMe

src/main/java/uk/gov/hmcts/opal/controllers/DefendantAccountController.java, src/main/java/uk/gov/hmcts/opal/controllers/NoteController.java, src/main/java/uk/gov/hmcts/opal/util/ResponseUtil.java, src/test/java/uk/gov/hmcts/opal/util/ResponseUtilTest.java
Refactor the duplicate code and reuse
```
[ ] Yes
[x] No
```
=> Refactor the duplicate code and reuse

charts/opal-fines-service/Chart.yaml, charts/opal-fines-service/values.dev.template.yaml, charts/opal-fines-service/values.stg.template.yaml, charts/opal-fines-service/values.yaml, docker-compose.yml, src/main/java/uk/gov/hmcts/opal/controllers/TestingSupportController.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/opal/controllers/TestingSupportControllerTest.java
PO-172
Make testing support controller behind a flag
```
[ ] Yes
[x] No
```
=> PO-172: Make testing support controller behind a flag

src/main/java/uk/gov/hmcts/opal/entity/CommittalWarrantProgressEntity.java, src/main/java/uk/gov/hmcts/opal/repository/AccountTransferRepository.java, src/main/java/uk/gov/hmcts/opal/repository/BusinessUnitRepository.java, src/main/java/uk/gov/hmcts/opal/repository/CommittalWarrentProgressRepository.java, src/main/java/uk/gov/hmcts/opal/repository/CourtRepository.java, src/main/java/uk/gov/hmcts/opal/repository/DebtorDetailRepository.java, src/main/java/uk/gov/hmcts/opal/repository/DocumentInstanceRepository.java, src/main/java/uk/gov/hmcts/opal/repository/DocumentRepository.java, src/main/java/uk/gov/hmcts/opal/repository/EnforcementRepository.java, src/main/java/uk/gov/hmcts/opal/repository/LocalJusticeAreaRepository.java, src/main/java/uk/gov/hmcts/opal/repository/MisDebtorRepository.java, src/main/java/uk/gov/hmcts/opal/repository/PartyRepository.java, src/main/java/uk/gov/hmcts/opal/repository/PaymentInRepository.java, src/main/java/uk/gov/hmcts/opal/repository/PaymentTermsRepository.java, src/main/java/uk/gov/hmcts/opal/repository/PrisonRepository.java, src/main/java/uk/gov/hmcts/opal/repository/TillRepository.java
=> Add new repositories for previously created entities

charts/opal-fines-service/Chart.yaml, charts/opal-fines-service/values.dev.template.yaml, charts/opal-fines-service/values.stg.template.yaml, charts/opal-fines-service/values.yaml
=> Point to staging instance for legacy stubs

src/main/java/uk/gov/hmcts/opal/dto/search/PartySearchDto.java, src/main/java/uk/gov/hmcts/opal/dto/search/PrisonSearchDto.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/AccountTransferSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/AddressSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/BaseCourtSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/BusinessUnitSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/CommittalWarrantProgressSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/CourtSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/DebtorDetailSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/EnforcementSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/EnforcerSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/EntitySpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/LocalJusticeAreaSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/MisDebtorSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/PartySpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/PaymentInSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/PaymentTermsSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/PrisonSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/TillSpecs.java
=> Implement more search critera for search endpoint

src/main/java/uk/gov/hmcts/opal/dto/search/BaseCourtSearch.java, src/main/java/uk/gov/hmcts/opal/dto/search/CourtSearchDto.java, src/main/java/uk/gov/hmcts/opal/dto/search/EnforcerSearchDto.java, src/main/java/uk/gov/hmcts/opal/dto/search/LocalJusticeAreaSearchDto.java, src/main/java/uk/gov/hmcts/opal/dto/search/PartySearchDto.java, src/main/java/uk/gov/hmcts/opal/dto/search/PrisonSearchDto.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/AddressSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/BaseCourtSpecs.java
=> Refine some of the entity searching

config/owasp/suppressions.xml
=> Fix for CVE-2023-6378

config/owasp/suppressions.xml
PO-204
Fix CVE-2023-35116
```
[ ] Yes
[ ] No
```
=> PO-204: Fix CVE-2023-35116

charts/opal-fines-service/values.dev.template.yaml, charts/opal-fines-service/values.yaml, config/owasp/suppressions.xml
=> Add launchdarkly secret to vault

src/functionalTest/resources/features/opalMode/defendantAccountAddNoteOpal.feature
=> quick fix for opal notes tests

src/functionalTest/java/uk/gov/hmcts/opal/steps/DefendantSearchApiStepDef.java, src/functionalTest/resources/features/legacyMode/defendantAccountSearchLegacy.feature, src/functionalTest/resources/features/opalMode/defendantAccountSearchOpal.feature, src/main/java/uk/gov/hmcts/opal/dto/legacy/DefendantAccountSearchCriteria.java, src/main/java/uk/gov/hmcts/opal/dto/search/AccountSearchDto.java, src/main/java/uk/gov/hmcts/opal/dto/search/PartySearchDto.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/DefendantAccountSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/PartySpecs.java, src/test/java/uk/gov/hmcts/opal/dto/AccountSearchDtoTest.java, src/test/java/uk/gov/hmcts/opal/repository/jpa/DefendantAccountSpecsTest.java
Address search now working across all 5 lines of Party address.
```
[ ] Yes
[*] No
```
=> Party search refinement

src/main/resources/db/migration/V20240219_090__add_aad_columns.sql
PO-191 added the SQL script to add the posted_by_aad column to 3 tables
```
[ ] Yes
[x] No
```
=> PO-191 added SQL script to add the posted_by_aad column to 3 tables

src/main/java/uk/gov/hmcts/opal/authentication/service/AccessTokenService.java, src/main/java/uk/gov/hmcts/opal/controllers/TestingSupportController.java, src/main/resources/db/migration/V20240219_090__add_aad_columns.sql, src/test/java/uk/gov/hmcts/opal/authentication/service/AccessTokenServiceTest.java, src/test/java/uk/gov/hmcts/opal/controllers/TestingSupportControllerTest.java
=> PO-220: Add endpoint to fetch token for a given user

src/main/java/uk/gov/hmcts/opal/authentication/service/AccessTokenService.java, src/main/java/uk/gov/hmcts/opal/authentication/service/TokenValidator.java, src/main/java/uk/gov/hmcts/opal/controllers/TestingSupportController.java, src/test/java/uk/gov/hmcts/opal/authentication/service/AccessTokenServiceTest.java, src/test/java/uk/gov/hmcts/opal/controllers/TestingSupportControllerTest.java
=> PO-180 Parse JWT token

build.gradle, src/functionalTest/java/uk/gov/hmcts/opal/steps/BearerTokenStefDef.java, src/functionalTest/java/uk/gov/hmcts/opal/steps/BearerTokenStepDef.java, src/functionalTest/java/uk/gov/hmcts/opal/steps/DefendantAccountAddNoteStepDef.java, src/functionalTest/java/uk/gov/hmcts/opal/steps/DefendantAccountDetailsStefDef.java, src/functionalTest/java/uk/gov/hmcts/opal/steps/DefendantSearchApiStepDef.java, src/functionalTest/java/uk/gov/hmcts/opal/steps/HealthApiStepDef.java, src/functionalTest/java/uk/gov/hmcts/opal/steps/NotesApiStepDef.java
https://tools.hmcts.net/jira/browse/PO-220
```
[ ] Yes
[ ] No
```
=> Integrate alt user tokens

src/main/java/uk/gov/hmcts/opal/authentication/service/AccessTokenService.java, src/test/java/uk/gov/hmcts/opal/authentication/service/AccessTokenServiceTest.java
=> Fix frontend flow

src/main/java/uk/gov/hmcts/opal/controllers/DefendantAccountController.java, src/main/java/uk/gov/hmcts/opal/controllers/NoteController.java, src/main/java/uk/gov/hmcts/opal/entity/BusinessUnitUserEntity.java, src/main/java/uk/gov/hmcts/opal/entity/UserEntitlementEntity.java, src/main/java/uk/gov/hmcts/opal/entity/UserEntity.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/UserEntitlementSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/UserSpecs.java, src/main/java/uk/gov/hmcts/opal/service/opal/BusinessUnitUserService.java, src/main/java/uk/gov/hmcts/opal/service/opal/UserEntitlementService.java, src/main/java/uk/gov/hmcts/opal/service/opal/UserService.java, src/main/java/uk/gov/hmcts/opal/service/opal/UserStateService.java, src/test/java/uk/gov/hmcts/opal/controllers/DefendantAccountControllerTest.java, src/test/java/uk/gov/hmcts/opal/controllers/NoteControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/BusinessUnitUserServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/UserEntitlementServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/UserServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/UserStateServiceTest.java
=> Implement more performant code for retrieving UserState

src/functionalTest/resources/features/opalMode/PO-184-187-188-192_addNote_postedBy_postedByAAD.feature
https://tools.hmcts.net/jira/browse/PO-184 
https://tools.hmcts.net/jira/browse/PO-187 
https://tools.hmcts.net/jira/browse/PO-188
https://tools.hmcts.net/jira/browse/PO-192
tests for above tickets
```
[ ] Yes
[ ] No
```
=> tests for @PO-184 @PO-187 @PO-188 @PO-192

src/integrationTest/java/uk/gov/hmcts/opal/authentication/controller/AuthenticationInternalUserControllerTest.java
=> PO-231: Add integration tests

.gitignore, src/main/java/uk/gov/hmcts/opal/controllers/FixedPenaltyOffenceController.java, src/main/java/uk/gov/hmcts/opal/controllers/ResultController.java, src/main/java/uk/gov/hmcts/opal/dto/search/FixedPenaltyOffenceSearchDto.java, src/main/java/uk/gov/hmcts/opal/dto/search/ResultSearchDto.java, src/main/java/uk/gov/hmcts/opal/entity/FixedPenaltyOffenceEntity.java, src/main/java/uk/gov/hmcts/opal/entity/ResultEntity.java, src/main/java/uk/gov/hmcts/opal/repository/FixedPenaltyOffenceRepository.java, src/main/java/uk/gov/hmcts/opal/repository/ResultRepository.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/EntitySpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/FixedPenaltyOffenceSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/ResultSpecs.java, src/main/java/uk/gov/hmcts/opal/service/FixedPenaltyOffenceServiceInterface.java, src/main/java/uk/gov/hmcts/opal/service/ResultServiceInterface.java, src/main/java/uk/gov/hmcts/opal/service/legacy/LegacyFixedPenaltyOffenceService.java, src/main/java/uk/gov/hmcts/opal/service/legacy/LegacyResultService.java, src/main/java/uk/gov/hmcts/opal/service/opal/FixedPenaltyOffenceService.java, src/main/java/uk/gov/hmcts/opal/service/opal/ResultService.java, src/main/java/uk/gov/hmcts/opal/service/proxy/FixedPenaltyOffenceServiceProxy.java, src/main/java/uk/gov/hmcts/opal/service/proxy/ResultServiceProxy.java, src/test/java/uk/gov/hmcts/opal/controllers/FixedPenaltyOffenceControllerTest.java, src/test/java/uk/gov/hmcts/opal/controllers/ResultControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/legacy/LegacyFixedPenaltyOffenceServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/legacy/LegacyResultServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/FixedPenaltyOffenceServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/ResultServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/proxy/FixedPenaltyOffenceServiceProxyTest.java, src/test/java/uk/gov/hmcts/opal/service/proxy/ResultServiceProxyTest.java
=> Add new entities: Result & FixedPenaltyOffence

src/main/java/uk/gov/hmcts/opal/authentication/controller/AuthenticationInternalUserController.java
=> PO-190: Add logs

src/main/java/uk/gov/hmcts/opal/controllers/DefendantAccountController.java
=> Temp: Notes search to just use Opal side

src/main/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandler.java, src/main/java/uk/gov/hmcts/opal/launchdarkly/FeatureDisabledException.java, src/main/java/uk/gov/hmcts/opal/launchdarkly/FeatureToggle.java, src/main/java/uk/gov/hmcts/opal/launchdarkly/FeatureToggleAspect.java, src/main/java/uk/gov/hmcts/opal/service/proxy/NoteServiceProxy.java, src/test/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandlerTest.java, src/test/java/uk/gov/hmcts/opal/launchdarkly/FeatureDisabledExceptionTest.java, src/test/java/uk/gov/hmcts/opal/launchdarkly/FeatureToggleAspectTest.java
=> PO-234: Feature toggle add note

charts/opal-fines-service/Chart.yaml, charts/opal-fines-service/values.stg.template.yaml, src/main/java/uk/gov/hmcts/opal/launchdarkly/FeatureToggleAspect.java
=> Fix master pipeline failure

src/functionalTest/java/uk/gov/hmcts/opal/steps/DefendantAccountAddNoteStepDef.java, src/functionalTest/resources/features/legacyMode/defendantAccountAddNoteLegacy.feature, src/functionalTest/resources/features/opalMode/PO-184-187-188-192_addNote_postedBy_postedByAAD.feature, src/functionalTest/resources/features/opalMode/defendantAccountAddNoteOpal.feature, src/main/java/uk/gov/hmcts/opal/authorisation/model/Permission.java, src/main/java/uk/gov/hmcts/opal/authorisation/model/Permissions.java, src/main/java/uk/gov/hmcts/opal/authorisation/model/Role.java, src/main/java/uk/gov/hmcts/opal/authorisation/model/UserState.java, src/main/java/uk/gov/hmcts/opal/config/properties/BeDeveloperConfiguration.java, src/main/java/uk/gov/hmcts/opal/controllers/DefendantAccountController.java, src/main/java/uk/gov/hmcts/opal/controllers/LoggingExceptionResolver.java, src/main/java/uk/gov/hmcts/opal/controllers/NoteController.java, src/main/java/uk/gov/hmcts/opal/dto/NoteDto.java, src/main/java/uk/gov/hmcts/opal/service/opal/UserService.java, src/main/java/uk/gov/hmcts/opal/service/opal/UserStateService.java, src/main/java/uk/gov/hmcts/opal/util/HttpUtil.java, src/main/java/uk/gov/hmcts/opal/util/PermissionUtil.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/opal/controllers/DefendantAccountControllerTest.java, src/test/java/uk/gov/hmcts/opal/controllers/LoggingExceptionResolverTest.java, src/test/java/uk/gov/hmcts/opal/controllers/NoteControllerTest.java, src/test/java/uk/gov/hmcts/opal/controllers/UserStateBuilder.java, src/test/java/uk/gov/hmcts/opal/service/opal/UserServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/UserStateServiceTest.java, src/test/java/uk/gov/hmcts/opal/util/PermissionUtilTest.java
Guard against unauthorised users adding a note to a defendant account.
```
[*] Yes
[ ] No
```
User now needs a role with the requisite permission in the correct business unit.
=> Ensure user has permission to 'addNote' to defendant account

Sample_text.txt, src/functionalTest/resources/features/opalMode/PO-184-187-188-192_addNote_postedBy_postedByAAD.feature, src/integrationTest/java/uk/gov/hmcts/opal/authentication/controller/AuthenticationInternalUserControllerTest.java, src/main/java/uk/gov/hmcts/opal/authorisation/model/UserState.java, src/main/java/uk/gov/hmcts/opal/controllers/DefendantAccountController.java, src/main/java/uk/gov/hmcts/opal/controllers/NoteController.java, src/main/java/uk/gov/hmcts/opal/dto/NoteDto.java, src/main/java/uk/gov/hmcts/opal/entity/DefendantTransactionEntity.java, src/main/java/uk/gov/hmcts/opal/entity/EnforcementEntity.java, src/main/java/uk/gov/hmcts/opal/entity/NoteEntity.java, src/main/java/uk/gov/hmcts/opal/entity/PaymentTermsEntity.java, src/main/java/uk/gov/hmcts/opal/entity/UserEntity.java, src/main/java/uk/gov/hmcts/opal/repository/BusinessUnitUserRepository.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/BusinessUnitUserSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/UserEntitlementSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/UserSpecs.java, src/main/java/uk/gov/hmcts/opal/service/opal/BusinessUnitUserService.java, src/main/java/uk/gov/hmcts/opal/service/opal/NoteService.java, src/main/resources/db/migration/V20240311_091__modify_users.sql, src/main/resources/db/migration/V20240312_092__insert_users_modified.sql, src/main/resources/db/migration/V20240312_093__update_business_unit_users.sql, src/main/resources/db/migration/V20240312_094__modify_business_unit_users.sql, src/test/java/uk/gov/hmcts/opal/authentication/controller/AuthenticationInternalUserControllerTest.java, src/test/java/uk/gov/hmcts/opal/authorisation/service/AuthorisationServiceTest.java, src/test/java/uk/gov/hmcts/opal/controllers/UserStateBuilder.java, src/test/java/uk/gov/hmcts/opal/service/opal/BusinessUnitUserServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/UserEntitlementServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/UserServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/UserStateServiceTest.java
=> Change UserId in UserEntity from String to Long

Sample_text.txt
=> Remove file

src/main/resources/db/migration/V20240318_095__insert_user_developer.sql
=> Add a 'developer' User to facilitate simpler BE development

src/functionalTest/java/uk/gov/hmcts/opal/steps/BearerTokenStepDef.java, src/main/java/uk/gov/hmcts/opal/authentication/service/AccessTokenService.java, src/main/java/uk/gov/hmcts/opal/authorisation/service/AuthorisationService.java, src/main/java/uk/gov/hmcts/opal/controllers/TestingSupportController.java, src/test/java/uk/gov/hmcts/opal/authorisation/service/AuthorisationServiceTest.java, src/test/java/uk/gov/hmcts/opal/controllers/TestingSupportControllerTest.java
=> PO-242 update test user endpoints to return user sate

.github/workflows/ci.yml
=> Fix PR pipeline issue

src/integrationTest/java/uk/gov/hmcts/opal/controllers/CourtControllerIntegrationTest.java
PO-254
Add integration tests
```
[ ] Yes
[x] No
```
=> PO-254: Add integration tests

src/integrationTest/java/uk/gov/hmcts/opal/controllers/CourtControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/controllers/CourtController.java, src/main/java/uk/gov/hmcts/opal/controllers/DefendantAccountController.java, src/main/java/uk/gov/hmcts/opal/service/opal/UserStateService.java, src/test/java/uk/gov/hmcts/opal/controllers/CourtControllerTest.java, src/test/java/uk/gov/hmcts/opal/controllers/DefendantAccountControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/UserStateServiceTest.java
=> Ensure endpoints are accessed with authorised user

src/integrationTest/java/uk/gov/hmcts/opal/controllers/DefendantAccountControllerIntegrationTest.java
=> PO-255 Add integration test for DefendantAccountController

src/integrationTest/java/uk/gov/hmcts/opal/controllers/CourtControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/DefendantAccountControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/controllers/CourtController.java, src/main/java/uk/gov/hmcts/opal/controllers/DefendantAccountController.java, src/main/java/uk/gov/hmcts/opal/controllers/LoggingExceptionResolver.java, src/main/java/uk/gov/hmcts/opal/controllers/develop/NoteController.java, src/main/java/uk/gov/hmcts/opal/service/opal/UserStateService.java, src/main/java/uk/gov/hmcts/opal/util/HttpUtil.java, src/test/java/uk/gov/hmcts/opal/controllers/CourtControllerTest.java, src/test/java/uk/gov/hmcts/opal/controllers/DefendantAccountControllerTest.java, src/test/java/uk/gov/hmcts/opal/controllers/develop/NoteControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/UserStateServiceTest.java
PO-262
Refactor and cleanup code
```
[ ] Yes
[x] No
```
=> PO-262: Refactor and cleanup code

src/functionalTest/java/uk/gov/hmcts/opal/steps/CourtSearchStepDef.java, src/functionalTest/java/uk/gov/hmcts/opal/steps/DefendantAccountDetailsStefDef.java, src/functionalTest/java/uk/gov/hmcts/opal/steps/DefendantAccountGetNoteStepDef.java, src/functionalTest/resources/features/opalMode/PO-250_authorisation.feature
https://tools.hmcts.net/jira/browse/PO-250
tests for PO-250
```
[ ] Yes
[ x ] No
```
=> PO-250 tests

src/main/java/uk/gov/hmcts/opal/authorisation/aspect/AuthorizationAspect.java, src/main/java/uk/gov/hmcts/opal/authorisation/aspect/AuthorizedAnyRoleHasPermission.java, src/main/java/uk/gov/hmcts/opal/service/opal/NoteService.java, src/main/java/uk/gov/hmcts/opal/service/proxy/DefendantAccountServiceProxy.java, src/test/java/uk/gov/hmcts/opal/authorisation/aspect/AuthorizationAspectTest.java
Correct typo in annotation name
```
[ ] Yes
[x] No
```
=> PO-265: Correct typo in annotation name

src/integrationTest/java/uk/gov/hmcts/opal/controllers/CourtControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/develop/BusinessUnitControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/develop/ConfigurationItemControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/develop/EnforcerControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/develop/ImpositionControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/develop/LocalJusticeAreaControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/develop/LogActionControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/develop/LogAuditDetailControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/develop/MajorCreditorControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/develop/OffenseControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/develop/ResultControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/develop/TillControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/entity/AddressEntity.java, src/main/java/uk/gov/hmcts/opal/entity/BusinessUnitEntity.java, src/main/java/uk/gov/hmcts/opal/entity/CourtEntity.java, src/main/java/uk/gov/hmcts/opal/entity/CreditorAccountEntity.java, src/main/java/uk/gov/hmcts/opal/entity/EnforcerCourtBaseEntity.java, src/main/java/uk/gov/hmcts/opal/entity/EnforcerEntity.java, src/main/java/uk/gov/hmcts/opal/entity/LocalJusticeAreaEntity.java, src/main/java/uk/gov/hmcts/opal/entity/MajorCreditorEntity.java, src/main/java/uk/gov/hmcts/opal/entity/PrisonEntity.java, src/test/java/uk/gov/hmcts/opal/entity/DefendantAccountEntityTest.java
=> New integration tests for reference data controllers, & some changes for consistency

src/integrationTest/java/uk/gov/hmcts/opal/controllers/BusinessUnitControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/controllers/BusinessUnitController.java, src/main/java/uk/gov/hmcts/opal/dto/reference/BusinessUnitReferenceDataResults.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/BusinessUnitSpecs.java, src/main/java/uk/gov/hmcts/opal/service/opal/BusinessUnitService.java, src/test/java/uk/gov/hmcts/opal/controllers/BusinessUnitControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/BusinessUnitServiceTest.java
=> PO-313 Add Business Unit reference data endpoint & infrastructure code

src/integrationTest/java/uk/gov/hmcts/opal/controllers/LocalJusticeAreaControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/controllers/BusinessUnitController.java, src/main/java/uk/gov/hmcts/opal/controllers/LocalJusticeAreaController.java, src/main/java/uk/gov/hmcts/opal/controllers/OffenceController.java, src/main/java/uk/gov/hmcts/opal/dto/reference/LjaReferenceDataResults.java, src/main/java/uk/gov/hmcts/opal/dto/search/LocalJusticeAreaSearchDto.java, src/main/java/uk/gov/hmcts/opal/entity/LocalJusticeAreaEntity.java, src/main/java/uk/gov/hmcts/opal/entity/projection/LjaReferenceData.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/LocalJusticeAreaSpecs.java, src/main/java/uk/gov/hmcts/opal/service/opal/LocalJusticeAreaService.java, src/test/java/uk/gov/hmcts/opal/controllers/LocalJusticeAreaControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/LocalJusticeAreaServiceTest.java
=> PO-312. Add LJA reference data endpoint & infrastructure code

src/integrationTest/java/uk/gov/hmcts/opal/controllers/CourtControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/develop/EnforcerControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/controllers/CourtController.java, src/main/java/uk/gov/hmcts/opal/dto/reference/CourtReferenceDataResults.java, src/main/java/uk/gov/hmcts/opal/entity/CourtEntity.java, src/main/java/uk/gov/hmcts/opal/entity/EnforcerCourtBaseEntity.java, src/main/java/uk/gov/hmcts/opal/entity/projection/CourtReferenceData.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/BaseCourtSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/CourtSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/LocalJusticeAreaSpecs.java, src/main/java/uk/gov/hmcts/opal/service/opal/CourtService.java, src/test/java/uk/gov/hmcts/opal/controllers/CourtControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/CourtServiceTest.java
=> PO-315: Add Court reference data endpoint & required infrastructure

src/integrationTest/java/uk/gov/hmcts/opal/controllers/BusinessUnitControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/controllers/BusinessUnitController.java, src/main/java/uk/gov/hmcts/opal/dto/reference/BusinessUnitReferenceDataResults.java, src/main/java/uk/gov/hmcts/opal/entity/BusinessUnitEntity.java, src/main/java/uk/gov/hmcts/opal/entity/projection/BusinessUnitReferenceData.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/BusinessUnitSpecs.java, src/main/java/uk/gov/hmcts/opal/service/opal/BusinessUnitService.java, src/test/java/uk/gov/hmcts/opal/controllers/BusinessUnitControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/BusinessUnitServiceTest.java
```
[ ] Yes
[*] Maybe
[ ] No
```
=> Tweaks to the Business Unit reference data

src/main/resources/db/migration/V20240521_155__enable_offence_business_units_fk.sql
PO-373
Put back business units id foreign key in the OFFENCES table after reference data load
```
[ ] Yes
[ x] No
```
=> PO-373 put back business unit id foreign key in the OFFENCES table

src/integrationTest/java/uk/gov/hmcts/opal/controllers/BusinessUnitControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/authorisation/model/Permissions.java, src/main/java/uk/gov/hmcts/opal/authorisation/model/UserState.java, src/main/java/uk/gov/hmcts/opal/controllers/BusinessUnitController.java, src/main/java/uk/gov/hmcts/opal/entity/BusinessUnitRef.java, src/main/java/uk/gov/hmcts/opal/entity/projection/BusinessUnitReferenceData.java, src/main/java/uk/gov/hmcts/opal/util/PermissionUtil.java, src/test/java/uk/gov/hmcts/opal/controllers/BusinessUnitControllerTest.java
=> PO-379: Add a 'permission' query parameter (filter) to the Business Unit reference data endpoint

src/main/resources/db/migration/V20240606_162__interface_files.sql, src/main/resources/db/migration/V20240606_163__interface_file_id_seq.sql
PO-356
PO-356 added scripts to create the Interface Files table and sequence
```
[ ] Yes
[ x] No
```
=> PO-356 added scripts to create the Interface Files table and sequence

src/main/resources/db/migration/V20240607_164__cleanup_courts.sql, src/main/resources/db/migration/V20240607_165__add_columns_to_courts.sql, src/main/resources/db/migration/V20240607_166__add_ILFPC_business_unit.sql, src/main/resources/db/migration/V20240607_167__courts_lja_id_null.sql, src/main/resources/db/migration/V20240611_169__update_da_enf_fk_court_ids.sql, src/main/resources/db/migration/V20240611_170__enable_courts_fks.sql
PO-308
PO-308 added sql scripts to load Courts reference data
```
[ ] Yes
[ x] No
```
=> PO-308 added sql scripts to load Courts reference data

src/integrationTest/java/uk/gov/hmcts/opal/controllers/MajorCreditorControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/controllers/MajorCreditorController.java, src/main/java/uk/gov/hmcts/opal/entity/projection/MajorCreditorReferenceData.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/MajorCreditorSpecs.java, src/main/java/uk/gov/hmcts/opal/service/opal/MajorCreditorService.java, src/test/java/uk/gov/hmcts/opal/controllers/MajorCreditorControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/MajorCreditorServiceTest.java
=> PO-421: Add business unit filtering to major creditor reference data query

src/main/resources/db/migration/V20240627_191__allocations.sql, src/main/resources/db/migration/V20240627_192__allocation_id_seq.sql
https://tools.hmcts.net/jira/browse/PO-392
These scripts create the ALLOCATIONS table and a sequence for the primary key.
```
[ ] Yes
[ X] No
```
=> PO-392 SQL scripts for ALLOCATIONS table

src/main/resources/db/migration/V20240627_193__court_fees_received.sql, src/main/resources/db/migration/V20240627_194__court_fee_received_id_seq.sql
https://tools.hmcts.net/jira/browse/PO-393
These scripts create the COURT_FEES_RECEIVED table and a sequence for the primary key.
```
[ ] Yes
[ X] No
```
=> PO-393 SQL scripts for COURT_FEES_RECEIVED table

build.gradle, json_schemas/batch_print_jobs_schema_v1.json, src/main/java/uk/gov/hmcts/opal/controllers/print/PrintRequestController.java, src/main/java/uk/gov/hmcts/opal/entity/print/PrintDefinition.java, src/main/java/uk/gov/hmcts/opal/entity/print/PrintJob.java, src/main/java/uk/gov/hmcts/opal/entity/print/PrintStatus.java, src/main/java/uk/gov/hmcts/opal/repository/print/PrintDefinitionRepository.java, src/main/java/uk/gov/hmcts/opal/repository/print/PrintJobRepository.java, src/main/java/uk/gov/hmcts/opal/service/print/PrintService.java, src/main/resources/db/migration/V20240628_195__insert_test_print_defintion.sql, src/main/resources/fop.xml, src/test/java/uk/gov/hmcts/opal/controllers/print/PrintRequestControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/print/PrintServiceTest.java
Part of P0-210
Printing code moved to the fines service.  Changes to json payload to accept data to be rendered as xml. 
```
[ ] Yes
[ X] No
```
=> print service code with xml in payload

.github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/publish-openapi.yaml, build.gradle
PO-494: 
Upgrade Java verion 21
```
[ ] Yes
[x] No
```
=> PO-494: Upgrade Java verion 21

src/main/java/uk/gov/hmcts/opal/authorisation/model/Permission.java, src/main/java/uk/gov/hmcts/opal/authorisation/model/Role.java, src/main/java/uk/gov/hmcts/opal/authorisation/model/UserState.java, src/main/java/uk/gov/hmcts/opal/service/opal/UserService.java, src/main/resources/application.yaml
PO-449:
Add redis cache for permissions/userState
```
[ ] Yes
[x] No
```
=> PO-449: Add redis cache for permissions/userState

README.md, docker-compose.yml
PO-449 
update readme
```
[ ] Yes
[x] No
```
=> PO-449 update readme

src/main/resources/db/migration/V20240701_196__cheques.sql, src/main/resources/db/migration/V20240701_197__cheque_id_seq.sql, src/main/resources/db/migration/V20240701_198__bacs_payments.sql, src/main/resources/db/migration/V20240701_199__bacs_payment_id_seq.sql, src/main/resources/db/migration/V20240701_200__report_instances.sql, src/main/resources/db/migration/V20240701_201__report_instance_id_seq.sql, src/main/resources/db/migration/V20240701_202__warrant_register.sql, src/main/resources/db/migration/V20240701_203__warrant_register_id_seq.sql, src/main/resources/db/migration/V20240701_204__standard_letters.sql, src/main/resources/db/migration/V20240701_205__standard_letter_id_seq.sql, src/main/resources/db/migration/V20240701_206__result_documents.sql, src/main/resources/db/migration/V20240701_207__result_document_id_seq.sql, src/main/resources/db/migration/V20240701_208__reports.sql, src/main/resources/db/migration/V20240701_209__control_totals.sql, src/main/resources/db/migration/V20240701_210__control_total_id_seq.sql, src/main/resources/db/migration/V20240701_211__hmrc_requests.sql, src/main/resources/db/migration/V20240701_212__hmrc_request_id_seq.sql, src/main/resources/db/migration/V20240701_213__report_entries.sql, src/main/resources/db/migration/V20240701_214__report_entry_id_seq.sql
https://tools.hmcts.net/jira/browse/PO-394
https://tools.hmcts.net/jira/browse/PO-395
https://tools.hmcts.net/jira/browse/PO-396
https://tools.hmcts.net/jira/browse/PO-397
https://tools.hmcts.net/jira/browse/PO-398
https://tools.hmcts.net/jira/browse/PO-399
https://tools.hmcts.net/jira/browse/PO-400
https://tools.hmcts.net/jira/browse/PO-401
https://tools.hmcts.net/jira/browse/PO-402
https://tools.hmcts.net/jira/browse/PO-403
All scripts have been successfully migrated using Flyway.
Create tables and sequences for the following tables ...
- CHEQUES
- BACS_PAYMENTS
- CONTROL_TOTALS
- WARRANT_REGISTER
- STANDARD_LETTERS
- RESULT_DOCUMENTS
- REPORTS (No sequence)
- HMRC_REQUESTS
- REPORT_INSTANCES
- REPORT_ENTRIES
```
[ ] Yes …
```
=> PO-394 to PO-403 Create Table and Sequence Scripts

README.md, docker-compose.yml
Disable redis cache by default in local env
```
[ ] Yes
[x] No
```
=> disable redis cache by default in local env

src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/controllers/DraftAccountController.java, src/main/java/uk/gov/hmcts/opal/dto/search/DraftAccountSearchDto.java, src/main/java/uk/gov/hmcts/opal/entity/DraftAccountEntity.java, src/main/java/uk/gov/hmcts/opal/repository/DraftAccountRepository.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/DraftAccountSpecs.java, src/main/java/uk/gov/hmcts/opal/service/DraftAccountServiceInterface.java, src/main/java/uk/gov/hmcts/opal/service/opal/DraftAccountService.java, src/test/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/DraftAccountServiceTest.java
=> PO-452: Add some initial code for Draft Accounts

src/main/resources/db/migration/V20240709_219__standard_letters_fk_report_entries_not_null.sql
https://tools.hmcts.net/jira/browse/PO-501
Renamed a foreign key constraint on the table STANDARD_LETTERS and set all columns in REPORT_ENTRIES table to not null.
```
[ ] Yes
[X ] No
```
=> PO-501 Fix minor issues with the CREATE TABLE scripts

src/main/java/uk/gov/hmcts/opal/controllers/develop/BacsPaymentController.java, src/main/java/uk/gov/hmcts/opal/dto/search/BacsPaymentSearchDto.java, src/main/java/uk/gov/hmcts/opal/entity/BacsPaymentEntity.java, src/main/java/uk/gov/hmcts/opal/repository/BacsPaymentRepository.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/BacsPaymentSpecs.java, src/main/java/uk/gov/hmcts/opal/service/BacsPaymentServiceInterface.java, src/main/java/uk/gov/hmcts/opal/service/legacy/LegacyBacsPaymentService.java, src/main/java/uk/gov/hmcts/opal/service/opal/BacsPaymentService.java, src/main/java/uk/gov/hmcts/opal/service/proxy/BacsPaymentServiceProxy.java, src/test/java/uk/gov/hmcts/opal/controllers/develop/BacsPaymentControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/legacy/LegacyBacsPaymentServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/BacsPaymentServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/proxy/BacsPaymentServiceProxyTest.java
```
[ ] Yes
[*} Probably the Pipelines
[ ] No
```
=> PO-495: Add infra code for BacsPayment

src/main/java/uk/gov/hmcts/opal/controllers/develop/ChequeController.java, src/main/java/uk/gov/hmcts/opal/dto/search/ChequeSearchDto.java, src/main/java/uk/gov/hmcts/opal/entity/ChequeEntity.java, src/main/java/uk/gov/hmcts/opal/repository/ChequeRepository.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/ChequeSpecs.java, src/main/java/uk/gov/hmcts/opal/service/ChequeServiceInterface.java, src/main/java/uk/gov/hmcts/opal/service/legacy/LegacyChequeService.java, src/main/java/uk/gov/hmcts/opal/service/opal/ChequeService.java, src/main/java/uk/gov/hmcts/opal/service/proxy/ChequeServiceProxy.java, src/test/java/uk/gov/hmcts/opal/controllers/develop/ChequeControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/legacy/LegacyChequeServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/ChequeServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/proxy/ChequeServiceProxyTest.java
```
[ ] Yes
[*] Probably the Pipelines
[ ] No
```
=> PO-495: Infra code for Cheques

src/integrationTest/java/uk/gov/hmcts/opal/controllers/BusinessUnitControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/entity/AliasEntity.java, src/main/java/uk/gov/hmcts/opal/entity/BusinessUnitEntity.java, src/main/java/uk/gov/hmcts/opal/entity/projection/BusinessUnitReferenceData.java, src/test/java/uk/gov/hmcts/opal/controllers/BusinessUnitControllerTest.java
=> PO-463: Add orgName to Alias and welshLanguage to BusinessUnit

README.md, src/functionalTest/java/uk/gov/hmcts/opal/steps/BearerTokenStepDef.java
Debug pipelines
```
[ ] Yes
[ ] No
```
=> Debug pipelines

src/main/java/uk/gov/hmcts/opal/controllers/develop/WarrantRegisterController.java, src/main/java/uk/gov/hmcts/opal/dto/search/WarrantRegisterSearchDto.java, src/main/java/uk/gov/hmcts/opal/entity/WarrantRegisterEntity.java, src/main/java/uk/gov/hmcts/opal/repository/WarrantRegisterRepository.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/WarrantRegisterSpecs.java, src/main/java/uk/gov/hmcts/opal/service/WarrantRegisterServiceInterface.java, src/main/java/uk/gov/hmcts/opal/service/legacy/LegacyWarrantRegisterService.java, src/main/java/uk/gov/hmcts/opal/service/opal/WarrantRegisterService.java, src/main/java/uk/gov/hmcts/opal/service/proxy/WarrantRegisterServiceProxy.java, src/test/java/uk/gov/hmcts/opal/controllers/develop/WarrantRegisterControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/legacy/LegacyWarrantRegisterServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/WarrantRegisterServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/proxy/WarrantRegisterServiceProxyTest.java
=> PO-495: Infra code for WarrantRegister

src/main/java/uk/gov/hmcts/opal/controllers/develop/ReportController.java, src/main/java/uk/gov/hmcts/opal/dto/search/ReportSearchDto.java, src/main/java/uk/gov/hmcts/opal/entity/ReportEntity.java, src/main/java/uk/gov/hmcts/opal/repository/ReportRepository.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/ReportSpecs.java, src/main/java/uk/gov/hmcts/opal/service/ReportServiceInterface.java, src/main/java/uk/gov/hmcts/opal/service/legacy/LegacyReportService.java, src/main/java/uk/gov/hmcts/opal/service/opal/ReportService.java, src/main/java/uk/gov/hmcts/opal/service/proxy/ReportServiceProxy.java, src/test/java/uk/gov/hmcts/opal/controllers/develop/ReportControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/legacy/LegacyReportServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/ReportServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/proxy/ReportServiceProxyTest.java
=> PO-495: Infra code for Reports

src/main/java/uk/gov/hmcts/opal/controllers/develop/StandardLetterController.java, src/main/java/uk/gov/hmcts/opal/dto/search/StandardLetterSearchDto.java, src/main/java/uk/gov/hmcts/opal/entity/StandardLetterEntity.java, src/main/java/uk/gov/hmcts/opal/repository/StandardLetterRepository.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/StandardLetterSpecs.java, src/main/java/uk/gov/hmcts/opal/service/StandardLetterServiceInterface.java, src/main/java/uk/gov/hmcts/opal/service/legacy/LegacyStandardLetterService.java, src/main/java/uk/gov/hmcts/opal/service/opal/StandardLetterService.java, src/main/java/uk/gov/hmcts/opal/service/proxy/StandardLetterServiceProxy.java, src/test/java/uk/gov/hmcts/opal/controllers/develop/StandardLetterControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/legacy/LegacyStandardLetterServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/StandardLetterServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/proxy/StandardLetterServiceProxyTest.java
=> PO-495: Infra code for StandardLetter

src/main/java/uk/gov/hmcts/opal/controllers/develop/ResultDocumentController.java, src/main/java/uk/gov/hmcts/opal/dto/search/ResultDocumentSearchDto.java, src/main/java/uk/gov/hmcts/opal/entity/ResultDocumentEntity.java, src/main/java/uk/gov/hmcts/opal/repository/ResultDocumentRepository.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/ResultDocumentSpecs.java, src/main/java/uk/gov/hmcts/opal/service/ResultDocumentServiceInterface.java, src/main/java/uk/gov/hmcts/opal/service/legacy/LegacyResultDocumentService.java, src/main/java/uk/gov/hmcts/opal/service/opal/ResultDocumentService.java, src/main/java/uk/gov/hmcts/opal/service/proxy/ResultDocumentServiceProxy.java, src/test/java/uk/gov/hmcts/opal/controllers/develop/ResultDocumentControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/legacy/LegacyResultDocumentServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/ResultDocumentServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/proxy/ResultDocumentServiceProxyTest.java
=> PO-495: Infra code for ResultDocument

src/main/java/uk/gov/hmcts/opal/controllers/develop/HmrcRequestController.java, src/main/java/uk/gov/hmcts/opal/dto/search/HmrcRequestSearchDto.java, src/main/java/uk/gov/hmcts/opal/entity/HmrcRequestEntity.java, src/main/java/uk/gov/hmcts/opal/repository/HmrcRequestRepository.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/HmrcRequestSpecs.java, src/main/java/uk/gov/hmcts/opal/service/HmrcRequestServiceInterface.java, src/main/java/uk/gov/hmcts/opal/service/legacy/LegacyHmrcRequestService.java, src/main/java/uk/gov/hmcts/opal/service/opal/HmrcRequestService.java, src/main/java/uk/gov/hmcts/opal/service/proxy/HmrcRequestServiceProxy.java, src/test/java/uk/gov/hmcts/opal/controllers/develop/HmrcRequestControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/legacy/LegacyHmrcRequestServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/HmrcRequestServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/proxy/HmrcRequestServiceProxyTest.java
=> PO-495: Infra code for HmrcRequest

src/integrationTest/java/uk/gov/hmcts/opal/controllers/OffenceControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/controllers/develop/ReportEntryController.java, src/main/java/uk/gov/hmcts/opal/controllers/develop/ReportInstanceController.java, src/main/java/uk/gov/hmcts/opal/dto/search/ReportEntrySearchDto.java, src/main/java/uk/gov/hmcts/opal/dto/search/ReportInstanceSearchDto.java, src/main/java/uk/gov/hmcts/opal/entity/ReportEntryEntity.java, src/main/java/uk/gov/hmcts/opal/entity/ReportInstanceEntity.java, src/main/java/uk/gov/hmcts/opal/repository/ReportEntryRepository.java, src/main/java/uk/gov/hmcts/opal/repository/ReportInstanceRepository.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/ReportEntrySpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/ReportInstanceSpecs.java, src/main/java/uk/gov/hmcts/opal/service/ReportEntryServiceInterface.java, src/main/java/uk/gov/hmcts/opal/service/ReportInstanceServiceInterface.java, src/main/java/uk/gov/hmcts/opal/service/legacy/LegacyReportEntryService.java, src/main/java/uk/gov/hmcts/opal/service/legacy/LegacyReportInstanceService.java, src/main/java/uk/gov/hmcts/opal/service/opal/ReportEntryService.java, src/main/java/uk/gov/hmcts/opal/service/opal/ReportInstanceService.java, src/main/java/uk/gov/hmcts/opal/service/proxy/ReportEntryServiceProxy.java, src/main/java/uk/gov/hmcts/opal/service/proxy/ReportInstanceServiceProxy.java, src/test/java/uk/gov/hmcts/opal/controllers/develop/ReportEntryControllerTest.java, src/test/java/uk/gov/hmcts/opal/controllers/develop/ReportInstanceControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/legacy/LegacyReportEntryServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/legacy/LegacyReportInstanceServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/ReportEntryServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/ReportInstanceServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/proxy/ReportEntryServiceProxyTest.java, src/test/java/uk/gov/hmcts/opal/service/proxy/ReportInstanceServiceProxyTest.java
```
[ ] Yes
[*} Maybe the Pipelines
[ ] No
```
=> PO-495: Add infrastructure code for new DB tables

src/main/java/uk/gov/hmcts/opal/service/opal/BusinessUnitService.java, src/main/java/uk/gov/hmcts/opal/service/opal/CourtService.java, src/main/java/uk/gov/hmcts/opal/service/opal/EnforcerService.java, src/main/java/uk/gov/hmcts/opal/service/opal/LocalJusticeAreaService.java, src/main/java/uk/gov/hmcts/opal/service/opal/MajorCreditorService.java, src/main/java/uk/gov/hmcts/opal/service/opal/OffenceService.java, src/test/java/uk/gov/hmcts/opal/authentication/service/SessionCacheTest.java
PO-491
Add cache for reference data
```
[ ] Yes
[x] No
```
=> PO-491 - Add cache for reference data

src/main/resources/db/migration/V20240723_221__add_welsh_lang_to_south_wales_bu.sql
https://tools.hmcts.net/jira/browse/PO-503
Sets the Welsh Language option to true for the South Wales business unit
```
[ ] Yes
[ X] No
```
=> PO-503 Add Welsh Language to South Wales BU

src/main/resources/db/migration/V20240723_222__user_permissions_collection_order.sql
https://tools.hmcts.net/jira/browse/PO-492
Adds the new functions and templates for Collection Orders.
Assigns this function to all users apart from User ID 500000001.
```
[ ] Yes
[X] No
```
=> PO-492 Create User Permissions for Collection Order

src/main/java/uk/gov/hmcts/opal/controllers/DraftAccountController.java, src/main/java/uk/gov/hmcts/opal/entity/DraftAccountEntity.java, src/main/java/uk/gov/hmcts/opal/service/opal/DraftAccountService.java, src/test/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/DraftAccountServiceTest.java
=> PO-511: Changes to Draft Accounts for Error Spike

src/main/java/uk/gov/hmcts/opal/service/opal/DefendantAccountService.java
=> PO-554: Logging level and details review code changes

src/integrationTest/java/uk/gov/hmcts/opal/controllers/ResultControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/controllers/ResultController.java, src/main/java/uk/gov/hmcts/opal/dto/reference/ResultReferenceDataResults.java, src/main/java/uk/gov/hmcts/opal/entity/projection/ResultReferenceData.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/ResultSpecs.java, src/main/java/uk/gov/hmcts/opal/service/opal/ResultService.java, src/test/java/uk/gov/hmcts/opal/controllers/ResultControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/ResultServiceTest.java
=> PO-314: Initial coding to support Result ref-data

src/main/resources/db/migration/V20240729_224__tidyup_configuration_items.sql, src/main/resources/db/migration/V20240729_225__insert_language_configuration_items.sql
PO-509
PO-509 introduce configuration items for welsh language preferences 
```
[ ] Yes
[ x] No
```
=> PO-509 introduce configuration items for welsh language preferences

src/main/java/uk/gov/hmcts/opal/authentication/aspect/UserStateAspectService.java, src/main/java/uk/gov/hmcts/opal/authentication/client/AzureTokenClient.java, src/main/java/uk/gov/hmcts/opal/authentication/client/OAuthClient.java, src/main/java/uk/gov/hmcts/opal/controllers/CourtController.java, src/main/java/uk/gov/hmcts/opal/controllers/DefendantAccountController.java, src/main/java/uk/gov/hmcts/opal/controllers/DraftAccountController.java, src/main/java/uk/gov/hmcts/opal/controllers/LoggingExceptionResolver.java, src/main/java/uk/gov/hmcts/opal/controllers/develop/NoteController.java, src/test/java/uk/gov/hmcts/opal/controllers/LoggingExceptionResolverTest.java
=> Restore LoggingExceptionResolver to capture/monitor/alter exceptions returned to Client

src/main/resources/db/migration/V20240806_228__update_welsh_bu_config.sql
https://tools.hmcts.net/jira/browse/PO-573
Updates and inserts new Welsh language preferences into the CONFIGURATION_ITEMS table.
```
[ ] Yes
[X ] No
```
=> PO-573 Update config items for Welsh BUs

src/main/java/uk/gov/hmcts/opal/controllers/ExceptionControllerAdvice.java, src/test/java/uk/gov/hmcts/opal/controllers/ExceptionControllerAdviceTest.java
```
[ ] Yes
[*] Probably Not
[ ] No
```
=> PO-511: Allow for custom HTTP response codes on error

src/main/java/uk/gov/hmcts/opal/controllers/ExceptionControllerAdvice.java, src/test/java/uk/gov/hmcts/opal/controllers/ExceptionControllerAdviceTest.java
=> PO-511: Tweaks to create 'cleaner' builds

src/main/java/uk/gov/hmcts/opal/controllers/CreateFineAccountsController.java, src/main/java/uk/gov/hmcts/opal/controllers/DebtorProfileSearchController.java
=> add swagger annotations

build.gradle, src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/controllers/DraftAccountController.java, src/main/java/uk/gov/hmcts/opal/dto/GetDraftAccountResponseDto.java, src/main/java/uk/gov/hmcts/opal/dto/ToJsonString.java, src/main/java/uk/gov/hmcts/opal/entity/DraftAccountEntity.java, src/main/java/uk/gov/hmcts/opal/exception/JsonSchemaValidationException.java, src/main/java/uk/gov/hmcts/opal/service/DraftAccountServiceInterface.java, src/main/java/uk/gov/hmcts/opal/service/opal/JsonSchemaValidationService.java, src/main/java/uk/gov/hmcts/opal/util/DateTimeUtils.java, src/main/java/uk/gov/hmcts/opal/util/KeepAsJsonDeserializer.java, src/main/resources/jsonSchemas/getDraftAccountResponse.json, src/test/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/JsonSchemaValidationServiceTest.java, src/test/resources/jsonSchemas/testSchema.json
```
[ ] Yes
[*] Yes, but not used anywhere yet
[ ] No
```
=> PO-591: GET Draft Account API implementation.

src/main/java/uk/gov/hmcts/opal/authentication/config/SecurityConfig.java, src/main/java/uk/gov/hmcts/opal/entity/OffenceEntity.java, src/main/java/uk/gov/hmcts/opal/entity/projection/OffenceReferenceData.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/OffenceSpecs.java, src/main/java/uk/gov/hmcts/opal/service/opal/OffenceService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/opal/controllers/OffenceControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/OffenceServiceTest.java
```
[ ] Yes
[*] No (fairly sure)
```
=> PO-614: Add dateUsedFrom to Offence Entity, add more data to ref-data response

src/main/java/uk/gov/hmcts/opal/exception/SchemaConfigurationException.java, src/main/java/uk/gov/hmcts/opal/service/opal/JsonSchemaValidationService.java, src/test/java/uk/gov/hmcts/opal/service/opal/JsonSchemaValidationServiceTest.java
```
[ ] Yes
[*] No, not yet
```
=> PO-559: Add schema config excepton

build.gradle, src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/controllers/DraftAccountController.java, src/main/java/uk/gov/hmcts/opal/dto/AddDraftAccountRequestDto.java, src/main/java/uk/gov/hmcts/opal/dto/DraftAccountResponseDto.java, src/main/java/uk/gov/hmcts/opal/dto/DraftAccountSnapshotsDto.java, src/main/java/uk/gov/hmcts/opal/dto/ToJsonString.java, src/main/java/uk/gov/hmcts/opal/entity/DraftAccountEntity.java, src/main/java/uk/gov/hmcts/opal/entity/DraftAccountStatus.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/DraftAccountSpecs.java, src/main/java/uk/gov/hmcts/opal/service/opal/DraftAccountService.java, src/main/java/uk/gov/hmcts/opal/service/opal/JsonSchemaValidationService.java, src/main/java/uk/gov/hmcts/opal/service/opal/UserStateService.java, src/main/resources/jsonSchemas/addDraftAccountRequest.json, src/test/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/DraftAccountServiceTest.java
=> PO-559: Update DraftAccount POST endpoint

.github/renovate.json, build.gradle, src/functionalTest/java/uk/gov/hmcts/opal/config/Constants.java, src/functionalTest/java/uk/gov/hmcts/opal/steps/GetResultsStepDef.java, src/functionalTest/resources/features/opalMode/results/PO-703_results.feature
https://tools.hmcts.net/jira/browse/PO-703
=> Po 703 tests

src/integrationTest/java/uk/gov/hmcts/opal/authentication/controller/AuthenticationInternalUserControllerTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/TestingSupportControllerTest.java, src/main/java/uk/gov/hmcts/opal/authorisation/aspect/AuthorizationAspect.java, src/main/java/uk/gov/hmcts/opal/authorisation/aspect/AuthorizationAspectService.java, src/main/java/uk/gov/hmcts/opal/authorisation/aspect/PermissionNotAllowedException.java, src/main/java/uk/gov/hmcts/opal/authorisation/model/BusinessUnitUserPermissions.java, src/main/java/uk/gov/hmcts/opal/authorisation/model/UserState.java, src/main/java/uk/gov/hmcts/opal/controllers/DefendantAccountController.java, src/main/java/uk/gov/hmcts/opal/controllers/develop/NoteController.java, src/main/java/uk/gov/hmcts/opal/service/opal/BusinessUnitUserService.java, src/main/java/uk/gov/hmcts/opal/service/opal/UserEntitlementService.java, src/main/java/uk/gov/hmcts/opal/util/PermissionUtil.java, src/test/java/uk/gov/hmcts/opal/authentication/aspect/LogAuditDetailsAspectTest.java, src/test/java/uk/gov/hmcts/opal/authentication/aspect/UserStateAspectServiceTest.java, src/test/java/uk/gov/hmcts/opal/authorisation/aspect/AuthorizationAspectServiceTest.java, src/test/java/uk/gov/hmcts/opal/authorisation/aspect/AuthorizationAspectTest.java, src/test/java/uk/gov/hmcts/opal/controllers/UserStateBuilder.java, src/test/java/uk/gov/hmcts/opal/service/opal/BusinessUnitUserServiceTest.java, src/test/java/uk/gov/hmcts/opal/util/PermissionUtilTest.java
```
[ ] Yes
[*] Hopefully Not
[ ] No
```
=> Rename 'Roles' class to 'BusinessUnitUserPermissions'

src/main/resources/db/migration/V20240920_257__assign_inputter_checker_permission.sql
PO-802
PO-802 make test user 1 both inputter and checker
```
[ x] Yes
[ ] No
```
=> PO-802 make test user 1 both an inputter and a checker

src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-559_getDraftAccount.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-591_createDraftAccount.feature, src/main/java/uk/gov/hmcts/opal/controllers/DraftAccountController.java, src/main/java/uk/gov/hmcts/opal/service/opal/DraftAccountService.java, src/test/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/DraftAccountServiceTest.java
submitted_by in disco + was username of logged on user, now it should be submitted_by field from json 
```
[ ] Yes
[ X] No
```
=> submitted_by to be value passed in json

src/main/resources/db/migration/V20240920_257__assign_inputter_checker_permission.sql
Reverts hmcts/opal-fines-service#546
=> Revert "PO-802 make test user 1 both an inputter and a checker"

src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/util/UserStateUtil.java, src/main/java/uk/gov/hmcts/opal/authorisation/aspect/PermissionNotAllowedException.java, src/main/java/uk/gov/hmcts/opal/authorisation/model/BusinessUnitUserPermissions.java, src/main/java/uk/gov/hmcts/opal/authorisation/model/UserState.java, src/main/java/uk/gov/hmcts/opal/controllers/DraftAccountController.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/BusinessUnitSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/DraftAccountSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/EntitySpecs.java, src/main/java/uk/gov/hmcts/opal/service/opal/DraftAccountService.java, src/main/java/uk/gov/hmcts/opal/service/opal/UserStateService.java, src/main/resources/jsonSchemas/getDraftAccountsResponse.json, src/test/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/DraftAccountServiceTest.java
```
[ ] Yes
[*] Partially
[ ] No
```
=> PO-606: GET multiple Draft Account summaries

src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountPostSteps.java, src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountPutSteps.java, src/functionalTest/java/uk/gov/hmcts/opal/utils/DataCleanUp.java, src/functionalTest/java/uk/gov/hmcts/opal/utils/DraftAccountUtils.java, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-746_putDraftAccount.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/accountJson/account.json
Tests for PO-746
https://tools.hmcts.net/jira/browse/PO-746
=> Tests for PO 746

src/main/java/uk/gov/hmcts/opal/entity/DebtorDetailEntity.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/DebtorDetailSpecs.java, src/main/resources/db/migration/V20240927_259__drop_debtor_detail_columns.sql
PO-655
PO-655 remove telephone and e-mail columns from DEBTOR_DETAIL table
```
[ ] Yes
[ x] No
```
=> PO-655 remove telophone and e-mail columns from DEBTOR_DETAIL table

src/functionalTest/java/uk/gov/hmcts/opal/steps/RefDataStepDef.java, src/main/java/uk/gov/hmcts/opal/controllers/OffenceController.java, src/main/java/uk/gov/hmcts/opal/service/opal/OffenceService.java
=> Fix offences ref-data caching & change query param to 'business_unit_id'

src/integrationTest/java/uk/gov/hmcts/opal/authentication/controller/AuthenticationInternalUserControllerTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/TestingSupportControllerTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/util/UserStateUtil.java, src/main/java/uk/gov/hmcts/opal/authorisation/aspect/AuthorizationAspect.java, src/main/java/uk/gov/hmcts/opal/authorisation/aspect/AuthorizationAspectService.java, src/main/java/uk/gov/hmcts/opal/authorisation/aspect/AuthorizedBusinessUnitUserHasPermission.java, src/main/java/uk/gov/hmcts/opal/authorisation/aspect/BusinessUnitUserNotFoundException.java, src/main/java/uk/gov/hmcts/opal/authorisation/aspect/BusinessUnitUserPermissionsNotFoundException.java, src/main/java/uk/gov/hmcts/opal/authorisation/aspect/PermissionNotAllowedException.java, src/main/java/uk/gov/hmcts/opal/authorisation/model/BusinessUnitUser.java, src/main/java/uk/gov/hmcts/opal/authorisation/model/UserState.java, src/main/java/uk/gov/hmcts/opal/controllers/DefendantAccountController.java, src/main/java/uk/gov/hmcts/opal/controllers/develop/NoteController.java, src/main/java/uk/gov/hmcts/opal/service/opal/BusinessUnitUserService.java, src/main/java/uk/gov/hmcts/opal/service/opal/UserEntitlementService.java, src/main/java/uk/gov/hmcts/opal/service/opal/UserService.java, src/main/java/uk/gov/hmcts/opal/util/PermissionUtil.java, src/test/java/uk/gov/hmcts/opal/authentication/aspect/LogAuditDetailsAspectTest.java, src/test/java/uk/gov/hmcts/opal/authentication/aspect/UserStateAspectServiceTest.java, src/test/java/uk/gov/hmcts/opal/authorisation/aspect/AuthorizationAspectServiceTest.java, src/test/java/uk/gov/hmcts/opal/authorisation/aspect/AuthorizationAspectTest.java, src/test/java/uk/gov/hmcts/opal/authorisation/aspect/PermissionNotAllowedExceptionTest.java, src/test/java/uk/gov/hmcts/opal/controllers/UserStateBuilder.java, src/test/java/uk/gov/hmcts/opal/service/opal/BusinessUnitUserServiceTest.java, src/test/java/uk/gov/hmcts/opal/util/PermissionUtilTest.java
=> PO-797: Rename BusinessUnitUserPermissions to BusinessUnitUser

src/functionalTest/java/uk/gov/hmcts/opal/steps/GenericExceptionPathStepDef.java, src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountPostSteps.java, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-690_getDraftAccountErrorHandling.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-691_postDraftAccountErrorHandling.feature, src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandler.java, src/test/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandlerTest.java
QA failure as:
Invalid JSON was returning HTTP 500 if it failed  our schema validation or 415 (unsupported media type) if it could not be unmarshalled.  Code has been refactored to return 400 (bad request)    
```
[ ] Yes
[ X] No
```
=> PO-691  bad request

src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/authorisation/model/UserState.java, src/main/java/uk/gov/hmcts/opal/controllers/DraftAccountController.java, src/main/java/uk/gov/hmcts/opal/service/opal/DraftAccountService.java, src/test/java/uk/gov/hmcts/opal/service/opal/DraftAccountServiceTest.java
PO-830
```
[ ] Yes
[ X] No
```
=> authorisation for put draft accounts

src/main/resources/db/migration/V20241008_265__message_log.sql
https://tools.hmcts.net/jira/browse/PO-665
Create the MESSAGE_LOG table 
```
[ ] Yes
[X] No
```
=> PO-665 Create MESSAGE_LOG table

build.gradle, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-830_putDraftAccountAuthorisation.feature
https://tools.hmcts.net/jira/browse/PO-830
Tests for PO-830
```
[ ] Yes
[x] No
```
=> tests for PO-830

src/main/resources/db/migration/V20241010_266__error_messages.sql
https://tools.hmcts.net/jira/browse/PO-666
Create the ERROR_MESSAGES table.
```
[ ] Yes
[X] No
```
=> PO-666 Create ERROR_MESSAGES table

src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountPostSteps.java, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/accountJson/account.json, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/accountJson/adultAccount.json, src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/util/UserStateUtil.java, src/main/java/uk/gov/hmcts/opal/authorisation/aspect/PermissionNotAllowedException.java, src/main/java/uk/gov/hmcts/opal/controllers/DraftAccountController.java, src/main/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandler.java, src/main/java/uk/gov/hmcts/opal/dto/AddDraftAccountRequestDto.java, src/main/java/uk/gov/hmcts/opal/dto/DraftAccountRequestDto.java, src/main/java/uk/gov/hmcts/opal/dto/ReplaceDraftAccountRequestDto.java, src/main/java/uk/gov/hmcts/opal/dto/ToJsonString.java, src/main/java/uk/gov/hmcts/opal/service/opal/DraftAccountService.java, src/main/resources/jsonSchemas/replaceDraftAccountRequest.json, src/test/java/uk/gov/hmcts/opal/authorisation/aspect/PermissionNotAllowedExceptionTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/DraftAccountServiceTest.java
=> PO-827: Add authorisation to draft account POST endpoint

src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/controllers/DraftAccountController.java, src/main/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandler.java, src/main/java/uk/gov/hmcts/opal/dto/DraftAccountResponseDto.java, src/main/java/uk/gov/hmcts/opal/dto/DraftAccountsResponseDto.java
=> PO-690: Add Exception Path handling for GET draft account endpoint

src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-827_postDraftAccountAuthorisation.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-831_patchDraftAccountAuthorisation.feature
https://tools.hmcts.net/jira/browse/PO-827
```
[ ] Yes
[ x] No
```
=> Po 827 tests

src/main/resources/db/migration/V20241021_270__aliases_surname_nullable.sql
PO-920
PO-920 Make the SURNAME column nullable in the ALIASES table
```
[ ] Yes
[ x] No
```
=> PO-920 Make the SURNAME column nullable in the ALIASES table

src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountGetSteps.java, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-690_getDraftAccountErrorHandling.feature
https://tools.hmcts.net/jira/browse/PO-690
```
[ ] Yes
[x ] No
```
=> Tests for PO-690

src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/controllers/DraftAccountController.java, src/main/java/uk/gov/hmcts/opal/interceptor/AcceptHeaderInterceptor.java, src/main/java/uk/gov/hmcts/opal/service/opal/DraftAccountService.java, src/main/resources/jsonSchemas/updateDraftAccountRequest.json, src/test/java/uk/gov/hmcts/opal/interceptor/AcceptHeaderInterceptorTest.java
747 / 749 
Some refactoring of exceptions thrown to meet common exception path AC and extra parameterised tests. 
```
[ ] Yes
[ X] No
```
=> Po 749 747 exception paths

src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/controllers/DraftAccountController.java, src/main/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandler.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/DraftAccountSpecs.java, src/main/java/uk/gov/hmcts/opal/service/opal/DraftAccountService.java, src/test/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerTest.java, src/test/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandlerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/DraftAccountServiceTest.java
```
[ ] Yes
[*] Probably Not
[ ] No
```
=> PO-832: Add not_submitted_by parameter to GET Draft Accounts

src/main/resources/db/migration/V20241031_274__change_item_values_to_json.sql
PO-904
PO-904 Change Configuration Items item_values to json
```
[ ] Yes
[ x] No
```
=> PO-904 Change Configuration Items item_values to json

src/functionalTest/java/uk/gov/hmcts/opal/config/Constants.java, src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountDeleteSteps.java, src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountGetSteps.java, src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountPostSteps.java, src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountPutSteps.java, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-828_getDraftAccountUserAuthorization.feature
=> tests for PO-828

src/main/resources/db/migration/V20241101_276__insert_user_defined_error_message.sql
PO-897
PO-897 load initially identified pre-defined error messages
```
[ ] Yes
[ x] No
```
=> PO-897 load initially identified pre-defined error messages

src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountPostSteps.java, src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountPutSteps.java, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-591_createDraftAccount.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-691_postDraftAccountErrorHandling.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-745_patchDraftAccount.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-746_putDraftAccount.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-747_patchDraftAccountErrorHandling.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-749_putDraftAccountErrorHandling.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-827_postDraftAccountAuthorisation.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-830_putDraftAccountAuthorisation.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-831_patchDraftAccountAuthorisation.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/getDraftAccountsMulti/PO-606_getDraftAccounts.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/getDraftAccountsMulti/PO-647_getDraftAccountsErrorHandling.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/getDraftAccountsMulti/PO-832_getDraftAccountsNotSubBy.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/getDraftAccountsSingle/PO-559_getDraftAccount.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/getDraftAccountsSingle/PO-690_getDraftAccountErrorHandling.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/getDraftAccountsSingle/PO-828_getDraftAccountUserAuthorization.feature, src/main/java/uk/gov/hmcts/opal/controllers/DraftAccountController.java, src/main/java/uk/gov/hmcts/opal/dto/AddDraftAccountRequestDto.java, src/main/java/uk/gov/hmcts/opal/dto/DraftAccountRequestDto.java, src/main/java/uk/gov/hmcts/opal/dto/DraftAccountResponseDto.java, src/main/java/uk/gov/hmcts/opal/dto/ReplaceDraftAccountRequestDto.java, src/main/java/uk/gov/hmcts/opal/entity/DraftAccountEntity.java, src/main/java/uk/gov/hmcts/opal/entity/DraftAccountSnapshots.java, src/main/java/uk/gov/hmcts/opal/service/opal/DraftAccountService.java, src/main/resources/db/migration/V20241111_278__add_columns_to_draft_accounts.sql, src/test/java/uk/gov/hmcts/opal/service/opal/DraftAccountServiceTest.java
PO-937: Add new columns submitted_by_name, account_status_date, status_message to the DRAFT_ACCOUNTS table
```
[*] Yes
[ ] No
```
=> PO-936: Add 'submitted_by_name' to Draft Accounts.

src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/controllers/DraftAccountController.java, src/main/java/uk/gov/hmcts/opal/dto/DraftAccountResponseDto.java, src/main/java/uk/gov/hmcts/opal/entity/DraftAccountEntity.java
=> PO-769: Add 'status_message' to Draft Accounts

src/main/java/uk/gov/hmcts/opal/entity/FixedPenaltyOffenceEntity.java, src/main/resources/db/migration/V20241122_279__add_vehicle_fixed_penalty.sql
PO-996
Add new column vehicle_fixed_penalty to the FIXED_PENALTY_OFFENCES table
```
[ ] Yes
[x ] No
```
=> Add new column vehicle_fixed_penalty to the FIXED_PENALTY_OFFENCES table

build.gradle, src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/MajorCreditorControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/controllers/MajorCreditorController.java, src/main/java/uk/gov/hmcts/opal/entity/ConfigurationItemEntity.java, src/main/java/uk/gov/hmcts/opal/entity/CreditorAccountEntity.java, src/main/java/uk/gov/hmcts/opal/entity/MajorCreditorEntity.java, src/main/java/uk/gov/hmcts/opal/entity/projection/MajorCreditorReferenceData.java, src/main/java/uk/gov/hmcts/opal/service/opal/MajorCreditorService.java, src/test/java/uk/gov/hmcts/opal/controllers/MajorCreditorControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/MajorCreditorServiceTest.java
=> PO-932: Add Creditor Account details to Major Creditor ref data.

src/integrationTest/java/uk/gov/hmcts/opal/controllers/OffenceControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/controllers/OffenceController.java, src/main/java/uk/gov/hmcts/opal/dto/reference/OffenceSearchDataResults.java, src/main/java/uk/gov/hmcts/opal/dto/search/OffenceSearchDto.java, src/main/java/uk/gov/hmcts/opal/entity/projection/OffenceSearchData.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/EntitySpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/OffenceSpecs.java, src/main/java/uk/gov/hmcts/opal/service/OffenceServiceInterface.java, src/main/java/uk/gov/hmcts/opal/service/legacy/LegacyOffenceService.java, src/main/java/uk/gov/hmcts/opal/service/opal/OffenceService.java, src/main/java/uk/gov/hmcts/opal/service/proxy/OffenceServiceProxy.java, src/test/java/uk/gov/hmcts/opal/controllers/OffenceControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/OffenceServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/proxy/OffenceServiceProxyTest.java
=> PO-926: Enhance POST Offences Search API Endpoint

src/main/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandler.java, src/main/java/uk/gov/hmcts/opal/service/opal/DraftAccountService.java, src/main/java/uk/gov/hmcts/opal/util/JsonPathUtil.java
=> A minor fix to the Draft Account POST endpoint processing.

src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountPatchSteps.java, src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountPostSteps.java, src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountPutSteps.java, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-745_patchDraftAccount.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/addDraftAccount/PO-591_createDraftAccount.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/addDraftAccount/PO-827_postDraftAccountAuthorisation.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/addDraftAccount/PO-936-postDraftAccountSubmittedByName.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/getDraftAccountsMulti/PO-606_getDraftAccounts.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/getDraftAccountsMulti/PO-832_getDraftAccountsNotSubBy.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/replaceDraftAccount/PO-746_putDraftAccount.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/replaceDraftAccount/PO-830_putDraftAccountAuthorisation.feature, src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java, src/main/resources/jsonSchemas/addDraftAccountRequest.json, src/main/resources/jsonSchemas/getDraftAccountResponse.json, src/main/resources/jsonSchemas/replaceDraftAccountRequest.json, src/main/resources/jsonSchemas/updateDraftAccountRequest.json, src/test/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerTest.java
=> make sure json schema refs are correct

src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java, src/main/resources/jsonSchemas/account.json
As title states
```
[ ] Yes
[ X] No
```
=> remove required status from nullable fields in json schema

src/main/java/uk/gov/hmcts/opal/controllers/DraftAccountController.java, src/main/java/uk/gov/hmcts/opal/service/opal/DraftAccountService.java, src/main/java/uk/gov/hmcts/opal/util/DateTimeUtils.java, src/test/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerTest.java
=> Method rename to show explicit conversion to UTC date time.

build.gradle, src/integrationTest/java/uk/gov/hmcts/opal/controllers/GetWelcomeTest.java, src/main/java/uk/gov/hmcts/opal/controllers/RootController.java, src/main/resources/application.yaml
=> Add a couple of log messages for welcome endpoint.

src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountDeleteSteps.java, src/functionalTest/java/uk/gov/hmcts/opal/utils/DataCleanUp.java, src/main/java/uk/gov/hmcts/opal/config/DatabaseConfiguration.java, src/main/java/uk/gov/hmcts/opal/controllers/DraftAccountController.java, src/main/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandler.java, src/main/java/uk/gov/hmcts/opal/service/opal/DraftAccountService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerTest.java, src/test/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandlerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/DraftAccountServiceTest.java
=> PO-1148. Add the Spring Boot setting for OSIV enable/disable and relevant code changes.

src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerTransientErrorsIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/authorisation/service/AuthorisationService.java, src/main/java/uk/gov/hmcts/opal/controllers/DraftAccountController.java, src/main/java/uk/gov/hmcts/opal/controllers/TestingSupportController.java, src/main/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandler.java, src/main/java/uk/gov/hmcts/opal/service/opal/BusinessUnitUserService.java, src/main/java/uk/gov/hmcts/opal/service/opal/DraftAccountService.java, src/main/java/uk/gov/hmcts/opal/service/opal/UserEntitlementService.java, src/main/java/uk/gov/hmcts/opal/service/opal/UserService.java, src/main/java/uk/gov/hmcts/opal/service/opal/proxy/DraftAccountServiceProxy.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerTest.java, src/test/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandlerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/DraftAccountServiceTest.java
=> PO-1148: Some code tidy relaated to JPA, Transaction boundaries, etc

gradle/wrapper/gradle-wrapper.properties, src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountPutSteps.java, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/replaceDraftAccount/PO-746_putDraftAccount.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/replaceDraftAccount/PO-830_putDraftAccountAuthorisation.feature, src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java, src/integrationTest/resources/db/draftAccounts/insert_into_draft_accounts.sql, src/main/java/uk/gov/hmcts/opal/controllers/DraftAccountController.java, src/main/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandler.java, src/main/java/uk/gov/hmcts/opal/dto/AddDraftAccountRequestDto.java, src/main/java/uk/gov/hmcts/opal/dto/DraftAccountResponseDto.java, src/main/java/uk/gov/hmcts/opal/dto/ReplaceDraftAccountRequestDto.java, src/main/java/uk/gov/hmcts/opal/dto/UpdateDraftAccountRequestDto.java, src/main/java/uk/gov/hmcts/opal/dto/Versioned.java, src/main/java/uk/gov/hmcts/opal/entity/DraftAccountEntity.java, src/main/java/uk/gov/hmcts/opal/exception/ResourceConflictException.java, src/main/java/uk/gov/hmcts/opal/service/opal/DraftAccountService.java, src/main/java/uk/gov/hmcts/opal/service/opal/util/VersionUtils.java, src/main/resources/application.yaml, src/main/resources/db/migration/devOnly/V20250206_279__column_version_number.sql, src/test/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandlerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/DraftAccountServiceTest.java
=> PO-1148 - Capture some idiomatic coding for handling optimistic locking.

charts/opal-fines-service/Chart.yaml
=> Update chart version

src/main/java/uk/gov/hmcts/opal/scheduler/job/FileHandlerJob.java, src/main/resources/application.yaml
=> PO-1394: Reduce log messages generated by Quartz jobs.

src/integrationTest/java/uk/gov/hmcts/opal/controllers/LocalJusticeAreaControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/MajorCreditorControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/OffenceControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/ResultControllerIntegrationTest.java
=> Traceability for integration tests

build.gradle, src/test/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandlerTest.java
Changes to resolve:
CVE-2024-38810, CVE-2024-38286, CVE-2024-38820, CVE-2025-25193, CVE-2025-24813
```
[ ] Yes
[ X] No
```
=> CVE resolution 

Jenkinsfile_CNP, build.gradle, src/functionalTest/java/uk/gov/hmcts/opal/scripts/TestReportSummaryGenerator.java, src/functionalTest/java/uk/gov/hmcts/opal/scripts/script.js, src/functionalTest/java/uk/gov/hmcts/opal/scripts/styles.css
=> feat(reporting): add HTML summary generation for test results

src/main/resources/db/migration/allEnvs/V20250409_305__enforcer_allocations.sql
https://tools.hmcts.net/jira/browse/PO-1276
PO-1276 Chi added script to create enforcer_allocations table
```
[ ] Yes
[x] No
```
=> PO-1276 Chi added script to create enforcer_allocations table

Jenkinsfile_nightly
=> setup nightly pipeline to run tests

Jenkinsfile_nightly
=> re-order nightly pipeline execution... maybe

Jenkinsfile_nightly
=> re-order nightly pipeline execution

Jenkinsfile_nightly
=> fix nightly pipeline

src/functionalTest/resources/features/opalMode/manualAccountCreation/offences/PO-614_newFieldsInOffenceAPI.feature
https://tools.hmcts.net/jira/browse/PO-1440
PO-1440 Chi loaded offences reference data from LIBRA live database
```
[ ] Yes
[x] No
```
=> PO-1440 Chi loaded offences reference data from LIBRA live database

src/functionalTest/java/uk/gov/hmcts/opal/steps/offences/SearchOffencesRequestStepDef.java, src/functionalTest/resources/features/opalMode/manualAccountCreation/offences/PO-614_newFieldsInOffenceAPI.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/offences/PO-926_offencesSearchApi.feature, src/integrationTest/java/uk/gov/hmcts/opal/controllers/BusinessUnitControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/CourtControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/LocalJusticeAreaControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/MajorCreditorControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/OffenceControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/ResultControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/dto/search/OffenceSearchDto.java, src/main/java/uk/gov/hmcts/opal/entity/projection/OffenceReferenceData.java, src/main/java/uk/gov/hmcts/opal/service/opal/OffenceService.java, src/main/resources/jsonSchemas/getBusinessUnitsRefDataResponse.json, src/main/resources/jsonSchemas/getCourtsRefDataResponse.json, src/main/resources/jsonSchemas/getLJARefDataResponse.json, src/main/resources/jsonSchemas/getMajorCredRefDataResponse.json, src/main/resources/jsonSchemas/getOffencesRefDataResponse.json, src/main/resources/jsonSchemas/getResultsRefDataResponse.json, src/main/resources/jsonSchemas/postCourtsSearchResponse.json, src/main/resources/jsonSchemas/postOffencesSearchResponse.json
=> PO-1446: Add Schemas for various Reference Datas

src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandler.java, src/test/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandlerTest.java
[PO-1061](https://tools.hmcts.net/jira/browse/PO-1061)
- Changed `detail` field in problem json to simple human readable string for display in UI rather than e.getMessage() where needed
- Centralised logging code  into helper method for error messages - logs appended with uuid/instance for full error message
```
[ ] Yes
[ X] No
```
=> PO-1061 error detail and logging refactor

build.gradle
Remove jitpack dependencies as they are now deprecated by HMCTS
```
[ ] Yes
[ X] No
```
=> remove jitpack dependencies

src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerTransientErrorsIntegrationTest.java, src/integrationTest/resources/db/draftAccounts/insert_into_draft_accounts.sql, src/main/java/uk/gov/hmcts/opal/controllers/DraftAccountController.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/DraftAccountSpecs.java, src/main/java/uk/gov/hmcts/opal/service/opal/DraftAccountService.java, src/main/java/uk/gov/hmcts/opal/service/opal/jpa/DraftAccountTransactions.java, src/test/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/DraftAccountServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/jpa/DraftAccountTransactionsTest.java
=> PO-946: Add new query params to GET Draft Account Summaries

src/integrationTest/java/uk/gov/hmcts/opal/controllers/BusinessUnitControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java, src/integrationTest/resources/db/draftAccounts/insert_into_business_units.sql, src/main/java/uk/gov/hmcts/opal/controllers/BusinessUnitController.java, src/main/java/uk/gov/hmcts/opal/service/opal/BusinessUnitService.java, src/main/resources/jsonSchemas/getBusinessUnitsRefDataResponse.json, src/test/java/uk/gov/hmcts/opal/service/opal/BusinessUnitServiceTest.java
=> PO-1047: Convert existing Business Unit Integration Tests over to using Test Containers

src/main/resources/jsonSchemas/legacy/getDefendantAccountLegacyRequest.json
https://tools.hmcts.net/jira/browse/PO-1609
```
[ ] Yes
[X ] No
```
=> Schema update, remove version from get request

src/main/resources/jsonSchemas/legacy/addNoteLegacyRequest.json, src/main/resources/jsonSchemas/legacy/getDefendantAccountLegacyRequest.json, src/test/java/uk/gov/hmcts/opal/json/DefendantAccountSummarySchemasTests.java
https://tools.hmcts.net/jira/browse/PO-1609
```
[ ] Yes
[X ] No
```
=> Schema update, add business_unit_id to legacy request

src/main/resources/jsonSchemas/legacy/addNoteLegacyResponse.json
New addNoteLegacyresponse.json
```
[ ] Yes
[X] No
```
=> addNoteLegacyResponse.json

src/main/resources/jsonSchemas/legacy/replaceDefendantAccountPartyLegacyResponse.json
new schema for replaceDefendantAccountPartyResponse
```
[ ] Yes
[ X] No
```
=> introduce replace defendant account party legacy response

src/integrationTest/java/uk/gov/hmcts/opal/controllers/GetWelcomeTest.java
=> PO-1047: Convert 'Welcome' Integration Test to using Test Containers

src/integrationTest/java/uk/gov/hmcts/opal/controllers/CourtControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/develop/ImpositionControllerIntegrationTest.java, src/integrationTest/resources/db/insertData/insert_into_courts.sql, src/main/java/uk/gov/hmcts/opal/controllers/CourtController.java, src/main/java/uk/gov/hmcts/opal/dto/legacy/search/LegacyCourtSearchResults.java, src/main/java/uk/gov/hmcts/opal/dto/reference/CourtReferenceData.java, src/main/java/uk/gov/hmcts/opal/dto/reference/CourtReferenceDataResults.java, src/main/java/uk/gov/hmcts/opal/dto/search/CourtSearchDto.java, src/main/java/uk/gov/hmcts/opal/entity/DefendantAccountEntity.java, src/main/java/uk/gov/hmcts/opal/entity/EnforcementEntity.java, src/main/java/uk/gov/hmcts/opal/entity/ImpositionEntity.java, src/main/java/uk/gov/hmcts/opal/entity/court/AbstractCourtEntity.java, src/main/java/uk/gov/hmcts/opal/entity/court/CourtEntity.java, src/main/java/uk/gov/hmcts/opal/mapper/CourtMapper.java, src/main/java/uk/gov/hmcts/opal/repository/CourtRepository.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/CourtSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/DefendantAccountSpecs.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/ImpositionSpecs.java, src/main/java/uk/gov/hmcts/opal/service/CourtServiceInterface.java, src/main/java/uk/gov/hmcts/opal/service/opal/CourtService.java, src/test/java/uk/gov/hmcts/opal/controllers/CourtControllerTest.java, src/test/java/uk/gov/hmcts/opal/entity/DefendantAccountEntityTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/CourtServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/DefendantAccountServiceTest.java
[PO-1447](https://tools.hmcts.net/jira/browse/PO-1447)
- Created a lite entity for courts with mapper to prevent joins to other tables - related changes tests etc. Based on schema I believe lite should be the default - we can extend the abstract entity  to create a full if needed later 
- Fields in DTOs aligned with schema from 1446 - related changes in specifications etc 
- lja field in schema mapped to local_justice_area_id. (note- not the lja db column)
```
[ ] Yes
[ x] No
```
=> Po 1447  courts 

src/main/java/uk/gov/hmcts/opal/controllers/BusinessUnitController.java, src/main/java/uk/gov/hmcts/opal/controllers/LocalJusticeAreaController.java, src/main/java/uk/gov/hmcts/opal/controllers/OffenceController.java, src/main/java/uk/gov/hmcts/opal/dto/legacy/search/LegacyOffenceSearchResults.java, src/main/java/uk/gov/hmcts/opal/dto/reference/BusinessUnitReferenceData.java, src/main/java/uk/gov/hmcts/opal/dto/reference/BusinessUnitReferenceDataResults.java, src/main/java/uk/gov/hmcts/opal/dto/reference/LjaReferenceData.java, src/main/java/uk/gov/hmcts/opal/dto/reference/LjaReferenceDataResults.java, src/main/java/uk/gov/hmcts/opal/dto/reference/OffenceReferenceData.java, src/main/java/uk/gov/hmcts/opal/dto/reference/OffenceReferenceDataResults.java, src/main/java/uk/gov/hmcts/opal/dto/reference/OffenceSearchData.java, src/main/java/uk/gov/hmcts/opal/dto/reference/OffenceSearchDataResults.java, src/main/java/uk/gov/hmcts/opal/entity/offence/AbstractOffenceEntity.java, src/main/java/uk/gov/hmcts/opal/entity/offence/OffenceEntity.java, src/main/java/uk/gov/hmcts/opal/entity/offence/OffenceEntityFull.java, src/main/java/uk/gov/hmcts/opal/mapper/OffenceMapper.java, src/main/java/uk/gov/hmcts/opal/repository/OffenceRepositoryFull.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/OffenceSpecs.java, src/main/java/uk/gov/hmcts/opal/service/opal/BusinessUnitService.java, src/main/java/uk/gov/hmcts/opal/service/opal/LocalJusticeAreaService.java, src/main/java/uk/gov/hmcts/opal/service/opal/OffenceService.java, src/test/java/uk/gov/hmcts/opal/controllers/BusinessUnitControllerTest.java, src/test/java/uk/gov/hmcts/opal/controllers/LocalJusticeAreaControllerTest.java, src/test/java/uk/gov/hmcts/opal/controllers/OffenceControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/BusinessUnitServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/LocalJusticeAreaServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/OffenceServiceTest.java
[PO-1447](https://tools.hmcts.net/jira/browse/PO-1447)
Lite entity introduced for POST (search) and GET offences  - full entity used for findById
```
[ ] Yes
[x] No
```
=> Po 1447 ref def refactor part 4 - offences - remove join to BU for GET and POST ref data

src/integrationTest/java/uk/gov/hmcts/opal/authentication/controller/AuthenticationInternalUserControllerTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/BusinessUnitControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/CourtControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/DefendantAccountControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerTransientErrorsIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/EnforcerControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/LocalJusticeAreaControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/MajorCreditorControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/OffenceControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/ResultControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/TestingSupportControllerTest.java, src/integrationTest/resources/db/insertData/insert_into_offences.sql, src/main/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandler.java
=> PO-1047: Integration Tests tidy and minor changes for Test Containers.

src/main/resources/application.yaml
=> New flyway locations for envs

src/main/resources/jsonSchemas/getDefendantAccountFixedPenaltyResponse.json, src/main/resources/jsonSchemas/legacy/getDefendantAccountFixedPenaltyLegacyRequest.json, src/main/resources/jsonSchemas/legacy/getDefendantAccountFixedPenaltyLegacyResponse.json, src/test/java/uk/gov/hmcts/opal/json/DefendantAccountFixedPenaltyTests.java
schemas and test for getDefendantFixedPenalty
```
[ ] Yes
[ X] No
```
=> Po 1672 1673 schemas for view defendant fixed penalty

src/main/resources/db/migration/allEnvs/V20250625_322__prosecutors.sql
PO-1433
PO-1433 create the PROSECUTORS table in opal fines database
```
[ ] Yes
[x] No
```
=> PO-1433 create the PROSECUTORS table in opal fines database

build.gradle, src/integrationTest/java/uk/gov/hmcts/opal/authentication/controller/AuthenticationInternalUserControllerTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/BusinessUnitControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/CourtControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/DefendantAccountControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerTransientErrorsIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/EnforcerControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/LocalJusticeAreaControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/MajorCreditorControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/OffenceControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/ResultControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/TestingSupportControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/develop/ConfigurationItemControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/develop/ImpositionControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/develop/LogActionControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/develop/LogAuditDetailControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/develop/TillControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/service/opal/DefendantAccountService.java, src/test/java/uk/gov/hmcts/opal/authorisation/aspect/AuthorizationAspectServiceTest.java, src/test/java/uk/gov/hmcts/opal/authorisation/aspect/AuthorizationAspectTest.java, src/test/java/uk/gov/hmcts/opal/controllers/TestingSupportControllerTest.java, src/test/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandlerTest.java, src/test/java/uk/gov/hmcts/opal/launchdarkly/FeatureToggleAspectTest.java, src/test/java/uk/gov/hmcts/opal/service/legacy/MockRestClient.java, src/test/java/uk/gov/hmcts/opal/service/opal/DefendantAccountServiceTest.java, src/test/java/uk/gov/hmcts/opal/sftp/SftpInboundServiceTest.java, src/test/java/uk/gov/hmcts/opal/sftp/SftpOutboundServiceTest.java
=> fix(deps): update dependency org.springdoc:springdoc-openapi-starter-webmvc-ui to v2.8.9

build.gradle, src/test/java/uk/gov/hmcts/opal/service/print/PrintServiceTest.java
=> fix(deps): update dependency org.apache.xmlgraphics:fop-core to v2.11

src/main/java/uk/gov/hmcts/opal/SchemaPaths.java, src/main/resources/jsonSchemas/opal/reference-data/getProsecutorsRefDataResponse.json
=> PO-1792: Add the JSON schema for GET Prosecutors reference data.

src/integrationTest/java/uk/gov/hmcts/opal/controllers/ProsecutorControllerIntegrationTest.java, src/integrationTest/resources/db/insertData/insert_into_prosecutors.sql, src/main/java/uk/gov/hmcts/opal/controllers/ProscutorController.java, src/main/java/uk/gov/hmcts/opal/dto/ToJsonString.java, src/main/java/uk/gov/hmcts/opal/dto/reference/ProsecutorReferenceData.java, src/main/java/uk/gov/hmcts/opal/dto/response/RefDataResponse.java, src/main/java/uk/gov/hmcts/opal/entity/ProsecutorEntity.java, src/main/java/uk/gov/hmcts/opal/entity/draft/TimelineData.java, src/main/java/uk/gov/hmcts/opal/mapper/ProsecutorMapper.java, src/main/java/uk/gov/hmcts/opal/repository/ProsecutorRepository.java, src/main/java/uk/gov/hmcts/opal/repository/jpa/ProsecutorSpecs.java, src/main/java/uk/gov/hmcts/opal/service/opal/ProsecutorService.java, src/test/java/uk/gov/hmcts/opal/controllers/ProsecutorControllerTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/ProsecutorServiceTest.java
=> PO-1787: Get Prosecutors API Endpoint

src/main/resources/db/migration/allEnvs/V20250627_325__add_index_draft_accounts.sql, src/main/resources/db/migration/allEnvs/V20250627_326__update_comments_draft_accounts.sql
PO-1439 and PO-1568
Added new index and updated comments on the DRAFT_ACCOUNTS table.
```
[ ] Yes
[x] No
```
=> PO-1439 and PO-1568 New index and updated comments on DRAFT_ACCOUNTS table

src/integrationTest/java/uk/gov/hmcts/opal/controllers/ProsecutorControllerIntegrationTest.java
=> PO-1787: Minor changes to the Prosecutors Integration Tests.

build.gradle
Update build.gradle to remove warnings
=> Fixed gradle warnings

src/main/resources/jsonSchemas/legacy/addNoteLegacyRequest.json, src/main/resources/jsonSchemas/legacy/common-objects/accountActivityNoteLegacy.json, src/test/java/uk/gov/hmcts/opal/json/DefendantAccountSummarySchemasTests.java
New schema for add note legacy request
```
[ ] Yes
[ ] No
```
=> New add note legacy request schema

src/main/resources/jsonSchemas/legacy/common-objects/accountLegacy.json, src/main/resources/jsonSchemas/legacy/common-objects/paymentTermsSummaryLegacy.json, src/main/resources/jsonSchemas/legacy/createDefendantAccountLegacyRequest.json
Fixed missing ref in paymentTerms schema
Updated createDefendantAccountRequest name for legacy and introduced legacy account schema
```
[ ] Yes
[ X] No
```
=> Legacy schema fixes

src/dbUnitTest/accountNumberTest/f_get_account_number_unit_tests.sql, src/integrationTest/resources/db/insertData/insert_into_defendants_for_deletion_test.sql, src/main/resources/db/migration/allEnvs/V20250710_329__f_get_check_letter.sql, src/main/resources/db/migration/allEnvs/V20250710_330__create_account_number_index.sql, src/main/resources/db/migration/allEnvs/V20250710_331__f_get_account_number.sql, src/main/resources/db/migration/allEnvs/V20250710_332__add_unique_index_defendant_accounts.sql, src/main/resources/db/migration/allEnvs/V20250710_333__add_unique_index_creditor_accounts.sql, src/main/resources/db/migration/allEnvs/V20250710_334__add_unique_index_miscellaneous_accounts.sql
https://tools.hmcts.net/jira/browse/PO-899
PO-899 - Create account number function, new table (account_number_index), unique index (account_number, business_unit_id) added to the defendant_accounts, creditor_accounts and miscellaneous_accounts tables.
```
[ ] Yes
[x] No
```
=> PO-899 Added scripts relating to create account number functions including new table

src/main/resources/jsonSchemas/legacy/updateDefendantAccountLegacyRequest.json, src/test/java/uk/gov/hmcts/opal/json/legacy/UpdateDefendantAccountLegacySchemaTests.java
Add business_unit_id and business_unit_user_id to update defendant account request
```
[ ] Yes
[ X] No
```
=> Add business_unit_id and business_unit_user_id to request

charts/opal-fines-service/values.dev.template.yaml
=> Updated role name

src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-745_patchDraftAccount.feature, src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/accountJson/adultAccount.json, src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java, src/integrationTest/resources/db/insertData/insert_into_draft_accounts.sql, src/main/java/uk/gov/hmcts/opal/entity/draft/DraftAccountEntity.java, src/main/java/uk/gov/hmcts/opal/entity/draft/StoredProcedureNames.java, src/main/java/uk/gov/hmcts/opal/mapper/DraftAccountMapper.java, src/main/java/uk/gov/hmcts/opal/repository/DraftAccountRepository.java, src/main/java/uk/gov/hmcts/opal/service/opal/DraftAccountPublish.java, src/main/java/uk/gov/hmcts/opal/service/opal/jpa/DraftAccountTransactions.java, src/test/java/uk/gov/hmcts/opal/service/opal/DraftAccountPublishTest.java, src/test/java/uk/gov/hmcts/opal/service/opal/jpa/DraftAccountTransactionsTest.java
=> PO-991: Draft Account publish with Opal Stored Proc.

Jenkinsfile_CNP, charts/opal-fines-service/values.dev.template.yaml, src/integrationTest/resources/application-legacy.yaml, src/integrationTest/resources/application-opal.yaml, src/main/java/uk/gov/hmcts/opal/config/properties/LaunchDarklyProperties.java, src/main/java/uk/gov/hmcts/opal/launchdarkly/FeatureToggleApi.java, src/test/java/uk/gov/hmcts/opal/launchdarkly/FeatureToggleApiTest.java
```
[ ] Yes
[*] Possibly
[ ] No
```
=> Tech Debt: Enable 'legacy' and 'opal' modes in Integration Tests.

src/main/resources/jsonSchemas/legacy/common-objects/businessUnitSummaryLegacy.json
Remove required business_unit_code
```
[ ] Yes
[ ] No
```
=> remove required business_unit_code

src/main/resources/jsonSchemas/opal/common-objects/accountActivityNote.json, src/main/resources/jsonSchemas/opal/common-objects/accountStatusReference.json, src/main/resources/jsonSchemas/opal/common-objects/addressDetails.json, src/main/resources/jsonSchemas/opal/common-objects/businessUnitSummary.json, src/main/resources/jsonSchemas/opal/common-objects/commentsAndNotes.json, src/main/resources/jsonSchemas/opal/common-objects/contactDetails.json, src/main/resources/jsonSchemas/opal/common-objects/defendantAccountParty.json, src/main/resources/jsonSchemas/opal/common-objects/employerDetails.json, src/main/resources/jsonSchemas/opal/common-objects/enforcementOverride.json, src/main/resources/jsonSchemas/opal/common-objects/enforcementStatusSummary.json, src/main/resources/jsonSchemas/opal/common-objects/fixedPenaltyTicketDetails.json, src/main/resources/jsonSchemas/opal/common-objects/individualAlias.json, src/main/resources/jsonSchemas/opal/common-objects/individualDetails.json, src/main/resources/jsonSchemas/opal/common-objects/instalmentPeriod.json, src/main/resources/jsonSchemas/opal/common-objects/languagePreference.json, src/main/resources/jsonSchemas/opal/common-objects/languagePreferences.json, src/main/resources/jsonSchemas/opal/common-objects/lastEnforcementAction.json, src/main/resources/jsonSchemas/opal/common-objects/ljaReference.json, src/main/resources/jsonSchemas/opal/common-objects/organisationAlias.json, src/main/resources/jsonSchemas/opal/common-objects/organisationDetails.json, src/main/resources/jsonSchemas/opal/common-objects/partyDetails.json, src/main/resources/jsonSchemas/opal/common-objects/paymentStateSummary.json, src/main/resources/jsonSchemas/opal/common-objects/paymentTermsSummary.json, src/main/resources/jsonSchemas/opal/common-objects/paymentTermsType.json, src/main/resources/jsonSchemas/opal/common-objects/vehicleDetails.json, src/main/resources/jsonSchemas/opal/common-objects/vehicleFixedPenaltyTicketDetails.json
=> introduce opal common-objects

src/main/resources/jsonSchemas/legacy/getDefendantAccountAtAGlanceLegacyResponse.json, src/main/resources/jsonSchemas/legacy/getDefendantAccountHeaderSummaryLegacyResponse.json
=> rename account_version to version for alignment

src/integrationTest/java/uk/gov/hmcts/opal/TestContainerConfig.java, src/integrationTest/java/uk/gov/hmcts/opal/controllers/LegacyDefendantAccountsIntegrationTest.java
=> PO-1907: Amendments regarding changes to proposed Legacy testing.

src/main/resources/jsonSchemas/legacy/postMinorCreditorAccountsSearchLegacyRequest.json, src/main/resources/jsonSchemas/legacy/postMinorCreditorsAccountsSearchLegacyResponse.json, src/main/resources/xsd/legacy/searchMinorCreditorAccountsResponse/creditor_accounts.xsd, src/main/resources/xsd/legacy/searchMinorCreditorAccountsResponse/creditor_accounts_element.xsd, src/main/resources/xsd/legacy/searchMinorCreditorAccountsResponse/defendant.xsd, src/main/resources/xsd/legacy/searchMinorCreditorAccountsResponse/error_response.xsd, src/main/resources/xsd/legacy/searchMinorCreditorAccountsResponse/search_minor_creditor_accounts_response.xsd
=> SearchMinorCreditorLegacyResponse XSD and some JSON alignment

src/main/resources/jsonSchemas/legacy/getDefendantAccountAtAGlanceLegacyResponse.json
=> fix ref from languagePreferenceLegacy to languagePreferencesLegacy

src/main/resources/xsd/legacy/searchDefendantAccountsResponse/aliases.xsd, src/main/resources/xsd/legacy/searchDefendantAccountsResponse/aliases_element.xsd, src/main/resources/xsd/legacy/searchDefendantAccountsResponse/defendant_account_element.xsd, src/main/resources/xsd/legacy/searchDefendantAccountsResponse/defendant_accounts.xsd, src/main/resources/xsd/legacy/searchDefendantAccountsResponse/error_response.xsd, src/main/resources/xsd/legacy/searchDefendantAccountsResponse/search_defendant_accounts_response.xsd
=> xsds for search_defendant_accounts_response legacy

src/main/resources/db/migration/allEnvs/V20250812_372__account_maintenance_note_perm.sql, src/main/resources/db/migration/allEnvs/V20250812_373__create_audit_amendment_fields.sql, src/main/resources/db/migration/allEnvs/V20250812_374__populate_audit_amendment_fields.sql
https://tools.hmcts.net/jira/browse/PO-1643
https://tools.hmcts.net/jira/browse/PO-1646
Add account maintenance permissions and create audit amendment fields
```
[ ] Yes
[x] No
```
=> PO-1643_1646 Add account maintenance permissions and create audit amendment fields

src/main/java/uk/gov/hmcts/opal/service/legacy/GatewayService.java, src/main/java/uk/gov/hmcts/opal/service/legacy/LegacyDefendantAccountService.java, src/main/java/uk/gov/hmcts/opal/service/legacy/LegacyDraftAccountPublish.java, src/main/java/uk/gov/hmcts/opal/service/legacy/LegacyGatewayService.java, src/main/java/uk/gov/hmcts/opal/util/XmlUtil.java, src/test/java/uk/gov/hmcts/opal/service/legacy/GatewayServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/legacy/LegacyDefendantAccountServiceTest.java, src/test/java/uk/gov/hmcts/opal/service/legacy/LegacyGatewayServiceTest.java, src/test/java/uk/gov/hmcts/opal/util/XmlUtilTest.java
=> PO-1907: Add Placeholder code for XML Schema validation of Legacy Responses.

src/main/resources/jsonSchemas/legacy/common-objects/partyDetailsLegacy.json, src/main/resources/jsonSchemas/opal/common-objects/partyDetails.json
=> rename party_id to defendant_account_party_id

src/main/resources/jsonSchemas/legacy/addDefendantAccountEnforcementLegacyRequest.json, src/main/resources/jsonSchemas/legacy/addDefendantAccountEnforcementLegacyResponse.json, src/main/resources/jsonSchemas/legacy/removeDefendantAccountEnforcementHoldLegacyRequest.json, src/main/resources/jsonSchemas/legacy/removeDefendantAccountEnforcementHoldLegacyResponse.json, src/main/resources/jsonSchemas/opal/common-objects/paymentTerms.json, src/main/resources/jsonSchemas/opal/defendant-account/addDefendantAccountEnforcementRequest.json, src/main/resources/jsonSchemas/opal/defendant-account/removeDefendantAccountEnforcementHoldRequest.json
=> Add remove enforcement actions schemas

src/main/resources/jsonSchemas/legacy/common-objects/enforcementOverrideLegacy.json, src/main/resources/jsonSchemas/legacy/common-objects/enforcementOverrideResultReferenceLegacy.json, src/main/resources/jsonSchemas/legacy/common-objects/enforcerReferenceLegacy.json, src/main/resources/jsonSchemas/legacy/common-objects/individualAliasLegacy.json, src/main/resources/jsonSchemas/legacy/common-objects/ljaReferenceLegacy.json, src/main/resources/jsonSchemas/legacy/common-objects/organisationAliasLegacy.json, src/main/resources/jsonSchemas/opal/common-objects/enforcementOverride.json, src/main/resources/jsonSchemas/opal/common-objects/enforcementOverrideResultReference.json, src/main/resources/jsonSchemas/opal/common-objects/enforcerReference.json, src/main/resources/jsonSchemas/opal/common-objects/individualAlias.json, src/main/resources/jsonSchemas/opal/common-objects/ljaReference.json, src/main/resources/jsonSchemas/opal/common-objects/organisationAlias.json
=> Update enforcement common-object structure

src/main/resources/jsonSchemas/opal/defendant-account/getDefendantAccountHeaderSummaryResponse.json
=> Update Defendant Account Header Summary schema inline with spec

src/main/resources/jsonSchemas/legacy/common-objects/partyDetailsLegacy.json, src/main/resources/jsonSchemas/opal/common-objects/partyDetails.json
=> partyChanges

src/main/resources/db/migration/allEnvs/V20250828_392__alter_payment_terms_add_reason_for_extension.sql, src/main/resources/db/migration/allEnvs/V20250828_393__alter_defendant_accounts_add_payment_card_requested_by_name.sql
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/PO-1853
https://tools.hmcts.net/jira/browse/PO-1855
Change description
PO-1853 - Add REASON_FOR_EXTENSION column to PAYMENT_TERMS table
PO-1855 - Add PAYMENT_CARD_REQUESTED_BY_NAME to DEFENDANT_ACCOUNTS table
[ ] Yes
[x] No
=> PO-1853 - Added reason_for_extension to payment_terms. PO-1855 - Added payment_card_requested_by_name to defendant_accounts

.github/renovate.json
=> Schedule renovate to run on Wednesdays only.

src/dbUnitTest/auditFinaliseTest/p_audit_finalise_unit_tests.sql, src/dbUnitTest/auditInitialiseTest/p_audit_initialise_unit_tests.sql, src/main/resources/db/migration/allEnvs/V20250902_395__p_audit_initialise.sql, src/main/resources/db/migration/allEnvs/V20250902_396__p_audit_finalise.sql
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/PO-1666
https://tools.hmcts.net/jira/browse/PO-1677
Change description
PO-1666 - Created procedure p_audit_initialise for auditing amendment list
PO-1677 - Created procedure p_audit_finalise for auditing amendment lists
[ ] Yes
[x] No
=> PO-1666_PO-1677 - Added database procedures for auditing amendment lists (initialise and finalise)

src/main/resources/jsonSchemas/legacy/updateDefendantAccountLegacyResponse.json
=> make defendant_account_id and version required in response

src/main/resources/jsonSchemas/legacy/addNoteLegacyResponse.json, src/main/resources/jsonSchemas/legacy/getDefendantAccountHeaderSummaryLegacyResponse.json, src/main/resources/jsonSchemas/opal/defendant-account/getDefendantAccountHeaderSummaryResponse.json
add debtor_type and is_youth to getDefendantAccountHeaderSummaryLegacyResponse.json and getDefendantAccountHeaderSummaryResponse.json
```
[ ] Yes
[ X] No
```
=> remove note_id from addNoteLegacyResponse.json

src/main/resources/jsonSchemas/legacy/getDefendantAccountPartyLegacyResponse.json, src/main/resources/jsonSchemas/legacy/replaceDefendantAccountPartyLegacyRequest.json, src/main/resources/jsonSchemas/legacy/replaceDefendantAccountPartyLegacyResponse.json, src/main/resources/jsonSchemas/opal/defendant-account/getDefendantAccountPartyResponse.json, src/main/resources/jsonSchemas/opal/defendant-account/replaceDefendantAccountPartyRequest.json
=> Change references to correct common object for parties

.github/renovate.json
=> Add renovate configuration options to curtail some aggressive upgrades.

src/main/resources/jsonSchemas/legacy/common-objects/noteLegacy.json, src/main/resources/jsonSchemas/opal/common-objects/note.json
=> fix enum value, remove space

src/main/resources/xsd/legacy/addNote/add_note_request.xsd, src/main/resources/xsd/legacy/addNote/add_note_response.xsd, src/main/resources/xsd/legacy/common-objects/account_status_reference.xsd, src/main/resources/xsd/legacy/common-objects/address_details.xsd, src/main/resources/xsd/legacy/common-objects/business_unit_summary.xsd, src/main/resources/xsd/legacy/common-objects/comments_and_notes.xsd, src/main/resources/xsd/legacy/common-objects/enforcement_override.xsd, src/main/resources/xsd/legacy/common-objects/enforcement_override_result_reference.xsd, src/main/resources/xsd/legacy/common-objects/enforcement_status_summary.xsd, src/main/resources/xsd/legacy/common-objects/enforcer_reference.xsd, src/main/resources/xsd/legacy/common-objects/error_response.xsd, src/main/resources/xsd/legacy/common-objects/individual_aliases.xsd, src/main/resources/xsd/legacy/common-objects/individual_aliases_element.xsd, src/main/resources/xsd/legacy/common-objects/individual_details.xsd, src/main/resources/xsd/legacy/common-objects/language.xsd, src/main/resources/xsd/legacy/common-objects/language_preferences.xsd, src/main/resources/xsd/legacy/common-objects/last_enforcement_action.xsd, src/main/resources/xsd/legacy/common-objects/lja_reference.xsd, src/main/resources/xsd/legacy/common-objects/note.xsd, src/main/resources/xsd/legacy/common-objects/organisation_aliases.xsd, src/main/resources/xsd/legacy/common-objects/organisation_aliases_element.xsd, src/main/resources/xsd/legacy/common-objects/organisation_details.xsd, src/main/resources/xsd/legacy/common-objects/party_details.xsd, src/main/resources/xsd/legacy/common-objects/payment_state_summary.xsd, src/main/resources/xsd/legacy/common-objects/payment_terms_summary.xsd, src/main/resources/xsd/legacy/common-objects/simple_type.xsd, src/main/resources/xsd/legacy/getDefendantAccountAtAGlance/get_defendant_account_at_a_glance_response.xsd, src/main/resources/xsd/legacy/getDefendantAccountAtAGlance/get_defendant_account_request.xsd, src/main/resources/xsd/legacy/getDefendantAccountHeaderSummary/get_defendant_account_header_summary_response.xsd, src/main/resources/xsd/legacy/getDefendantAccountHeaderSummary/get_defendant_account_request.xsd
=> Defendant account summary xsd

src/main/resources/jsonSchemas/legacy/getDefendantAccountEnforcementStatusLegacyResponse.json
Fixed issue with getDefendantAccountEnforcementStatusLegacyResponse.json
=> Fixed issue with getDefendantAccountEnforcementStatusLegacyResponse.json

build.gradle, charts/opal-fines-service/Chart.yaml, charts/opal-fines-service/values.yaml
Tidied up some code / added comment for temp overrides
=> Tidied up some code / added comment for temp overrides

src/main/resources/xsd/legacy/common-objects/contact_details.xsd, src/main/resources/xsd/legacy/common-objects/creditor_account_type_reference.xsd, src/main/resources/xsd/legacy/common-objects/defendant_account_party.xsd, src/main/resources/xsd/legacy/common-objects/employer_details.xsd, src/main/resources/xsd/legacy/common-objects/simple_type.xsd, src/main/resources/xsd/legacy/common-objects/vehicle_details.xsd, src/main/resources/xsd/legacy/getMinorCreditor/get_minor_creditor_account_at_a_glance_response.xsd, src/main/resources/xsd/legacy/getMinorCreditor/get_minor_creditor_account_header_summary_response.xsd, src/main/resources/xsd/legacy/getMinorCreditor/minor_creditor_account_id_request.xsd
https://tools.hmcts.net/jira/browse/PO-2022
https://tools.hmcts.net/jira/browse/PO-2023
```
[ ] Yes
[ X] No
```
=>  PO-2022 & PO-2023 XSDs for baseline getMinorCreditors HS & AAG

src/main/resources/jsonSchemas/legacy/common-objects/collectionOrderLegacy.json, src/main/resources/jsonSchemas/legacy/updateDefendantAccountLegacyRequest.json, src/main/resources/jsonSchemas/legacy/updateDefendantAccountLegacyResponse.json, src/main/resources/jsonSchemas/opal/defendant-account/updateDefendantAccountRequest.json
https://tools.hmcts.net/jira/browse/PO-2054
```
[ ] Yes
[X ] No
```
=> PO-2054 rework update defendant account legacy schema

src/integrationTest/java/uk/gov/hmcts/opal/controllers/DefendantAccountsControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/opal/dto/GetDefendantAccountPaymentTermsResponse.java, src/main/java/uk/gov/hmcts/opal/dto/PaymentTerms.java, src/main/java/uk/gov/hmcts/opal/dto/legacy/LegacyGetDefendantAccountPaymentTermsResponse.java, src/main/java/uk/gov/hmcts/opal/dto/legacy/LegacyPaymentTerms.java, src/main/java/uk/gov/hmcts/opal/service/legacy/LegacyDefendantAccountService.java, src/main/java/uk/gov/hmcts/opal/service/opal/OpalDefendantAccountService.java, src/main/resources/jsonSchemas/legacy/addDefendantAccountPaymentTermsLegacyResponse.json, src/main/resources/jsonSchemas/legacy/common-objects/paymentTermsLegacy.json, src/main/resources/jsonSchemas/legacy/getDefendantAccountPaymentTermsLegacyResponse.json, src/main/resources/jsonSchemas/opal/common-objects/paymentTerms.json, src/main/resources/jsonSchemas/opal/common-objects/postedDetails.json, src/main/resources/jsonSchemas/opal/defendant-account/getDefendantAccountPaymentTermsResponse.json, src/test/java/uk/gov/hmcts/opal/service/legacy/LegacyDefendantAccountServiceTest.java
https://tools.hmcts.net/jira/browse/PO-2033
https://tools.hmcts.net/jira/browse/PO-2032
```
[ ] Yes
[ X] No
```
=> PO-2033-2032 Payment terms schema changes
